//Platform-branching device capability accessors (no React). Hooks in
//`@arrzdev/adaptv/hooks` wrap these; import them directly for non-React wiring —
//e.g. feeding `getOnline`/`subscribeOnline` into TanStack Query's `onlineManager`.
export * from "../capabilities/app-state"
export * from "../capabilities/back-chain"
export * from "../capabilities/browser"
export * from "../capabilities/clipboard"
export * from "../capabilities/device"
export * from "../capabilities/geolocation"
export * from "../capabilities/gesture-controller"
export * from "../capabilities/haptic-tick"
export * from "../capabilities/haptics"
export * from "../capabilities/keep-awake"
export * from "../capabilities/keyboard"
export * from "../capabilities/native-theme"
export * from "../capabilities/network"
export * from "../capabilities/orientation"
export * from "../capabilities/share"
export * from "../capabilities/splash"
export * from "../capabilities/status-bar"
