// @vitest-environment node
import { describe, expect, it } from "vitest"
import {
  ADAPTV_DIR,
  ADAPTV_GITIGNORED,
  nextGitignore,
} from "#adaptv/vite/adaptv-dir"

// adaptv generates `capacitor.config.json` at the app root (the Capacitor CLI requires it
// in the directory it runs from, so it can't live in `.adaptv/`) and `adaptv dev` mutates
// it in place — `server.url`, `errorPath`, `androidScheme`. Committed, a run killed with
// SIGKILL leaves dev fields in a tracked file, one `git commit -a` from shipping an app
// that points at a laptop. Ignoring it is the fix, which means the ignore list has to be
// able to GROW for apps that were set up before an entry existed. → config-artifact PR.

describe("nextGitignore — cover everything adaptv generates, without rewriting the file", () => {
  it("writes the full stanza when nothing is ignored yet", () => {
    const next = nextGitignore("")
    expect(next).not.toBeNull()
    for (const entry of ADAPTV_GITIGNORED) {
      expect(next).toContain(entry)
    }
    // the explanatory comment rides along on the first write
    expect(next).toContain("# Generated by adaptv")
  })

  it("tops up a missing entry for an app that already ignores .adaptv/", () => {
    // the regression this guards: bailing on the FIRST match would leave these apps
    // committing capacitor.config.json forever.
    const existing = `node_modules\n${ADAPTV_DIR}/\n`
    const next = nextGitignore(existing)
    expect(next).not.toBeNull()
    expect(next).toContain("capacitor.config.json")
    // …and doesn't repeat the comment or re-add what's already there
    expect(next).not.toContain("# Generated by adaptv")
    expect(next?.match(new RegExp(`${ADAPTV_DIR}/`, "g"))?.length).toBe(1)
  })

  it("is a no-op once everything is covered", () => {
    const covered = `node_modules\n${ADAPTV_GITIGNORED.join("\n")}\n`
    expect(nextGitignore(covered)).toBeNull()
  })

  it("never reorders or drops what the consumer already had", () => {
    const existing = "dist\n.env.local\nnode_modules\n"
    const next = nextGitignore(existing) ?? ""
    expect(next.startsWith(existing)).toBe(true)
  })

  it("does not glue an entry onto a file with no trailing newline", () => {
    const next = nextGitignore("node_modules") ?? ""
    expect(next).not.toContain("node_modules.adaptv")
    expect(next.split(/\r?\n/)).toContain("node_modules")
  })
})
