/**
 * `.nativ/` — the hidden generated directory. → `ARCHITECTURE.md §3.2` (D1)
 *
 * ## Why hide them rather than eliminate them
 *
 * Fully removing generated files is out of scope and would be a mistake: TanStack
 * Router's typesafety **rests on** a generated route tree, and killing it means
 * forking the type layer — which violates the "rent the stable core, own the
 * seams" doctrine (§0.6). So the goal is not absence, it is **opacity**: the files
 * still exist, they are just not the consumer's problem.
 *
 * Before this, the plugin stamped into the app's own source tree —
 * `src/router.gen.tsx`, `src/routing/layouts/__root.gen.tsx`, `routeTree.gen.ts`
 * beside the routes. Three framework artifacts interleaved with application code,
 * each needing its own `.gitignore` line, each showing up in search results and
 * file trees forever.
 *
 * One dot-prefixed directory, regenerated on every `dev`/`build`, gitignored, and
 * treated exactly like `dist/`. The consumer wires none of it: nativ emits the
 * tsconfig `paths` mapping, the Vite alias, and the ignore entry itself.
 */
import path from "node:path"

/** The generated directory, relative to the app root. */
export const NATIV_DIR = ".nativ"

/**
 * The alias generated code uses to reach into `.nativ/`.
 *
 * A distinct namespace from `#nativ/*` (which is the framework's own internal
 * self-alias) so the two can never be confused when reading a stack trace.
 */
export const NATIV_GEN_ALIAS = "#nativ-gen"

export type GeneratedPaths = {
  /** The stamped router entry (`createRouter` + the Register declaration). */
  routerGen: string
  /** The generated service worker, when the app does not author its own. */
  swGen: string
  /** TanStack's generated route tree. */
  routeTree: string
  /** The `declare module` augmentation that lights up typed routing. */
  registerDts: string
}

/**
 * ⚠︎ The root route is deliberately NOT here.
 *
 * It is a real module shipped in the package (`src/routes/root-route.tsx`); the
 * virtual-route DSL points at it via `NATIV_ROOT_ROUTE_FILE`, and its
 * app-specific half arrives through the `virtual:nativ/root-route` module. It was
 * generated per-app until an audit showed almost all of it was framework code.
 */

/** Absolute paths of everything nativ generates, for an app at `appRoot`. */
export function resolveGeneratedPaths(appRoot: string): GeneratedPaths {
  const dir = path.join(appRoot, NATIV_DIR)
  return {
    routerGen: path.join(dir, "router.gen.tsx"),
    swGen: path.join(dir, "sw.gen.ts"),
    routeTree: path.join(dir, "routeTree.gen.ts"),
    registerDts: path.join(dir, "register.d.ts"),
  }
}

/**
 * The `compilerOptions.paths` entry an app's tsconfig needs.
 *
 * Emitted by nativ rather than documented for the consumer to copy: a path
 * mapping that must stay in sync with a framework internal is precisely the kind
 * of per-project wiring that rots silently.
 */
export function nativDirTsconfigPaths(): Record<string, string[]> {
  return { [`${NATIV_GEN_ALIAS}/*`]: [`./${NATIV_DIR}/*`] }
}

/** The `.gitignore` stanza for the generated dir. */
export function nativDirGitignoreEntry(): string {
  return [
    "# Generated by nativ on every dev/build. A build artifact, like dist/.",
    `${NATIV_DIR}/`,
  ].join("\n")
}
