import type { Plugin } from "vite"
import type { AdaptvAppConfig } from "#adaptv/config/app-config.ts"
import {
  ROUTER_BUILD_KEYS,
  resolveThemeColors,
} from "#adaptv/config/app-config.ts"
import type { AdaptvContext } from "#adaptv/vite/adaptv-context.ts"
import { requireAppConfig } from "#adaptv/vite/adaptv-context.ts"
import {
  defaultIconFiles,
  headIconLinks,
  resolveIconSet,
} from "#adaptv/vite/icon-set.ts"
import { serializeValue } from "#adaptv/vite/serialize.ts"
import { extractThunkSpecifier } from "#adaptv/vite/thunk-specifiers.ts"

/** Virtual module id the shipped root route imports. */
export const ROOT_ROUTE_VIRTUAL_ID = "virtual:adaptv/root-route"
const RESOLVED_ROOT_ROUTE_ID = `\0${ROOT_ROUTE_VIRTUAL_ID}`

/** Virtual module carrying the app's `createRouter` options. */
export const ROUTER_CONFIG_VIRTUAL_ID = "virtual:adaptv/router-config"
const RESOLVED_ROUTER_CONFIG_ID = `\0${ROUTER_CONFIG_VIRTUAL_ID}`

/** Router options from `adaptv.config.ts`, as a module. Values only — no types needed. */
export function renderRouterConfigModule(config: AdaptvAppConfig): string {
  const router = config.router
  const options: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(router)) {
    if (NON_CREATE_ROUTER_KEYS.has(key)) continue
    options[key] = value
  }
  return [
    BANNER,
    `export const routerOptions = {`,
    `  memoryHistoryInStandalone: ${JSON.stringify(
      router.memoryHistoryInStandalone ?? false,
    )},`,
    `  options: ${serializeValue(options)},`,
    "}",
    "",
  ].join("\n")
}

/** Serve `virtual:adaptv/root-route` and `virtual:adaptv/router-config`. */
export function adaptvRootRoutePlugin(
  context: AdaptvContext,
  routerSpecifier?: string,
): Plugin {
  return {
    name: "adaptv:root-route",
    resolveId(id) {
      if (id === ROOT_ROUTE_VIRTUAL_ID) return RESOLVED_ROOT_ROUTE_ID
      if (id === ROUTER_CONFIG_VIRTUAL_ID) return RESOLVED_ROUTER_CONFIG_ID
      return null
    },
    load(id) {
      if (id === RESOLVED_ROUTER_CONFIG_ID) {
        return renderRouterConfigModule(requireAppConfig(context))
      }
      if (id !== RESOLVED_ROOT_ROUTE_ID) return null
      const config = requireAppConfig(context)
      // Resolved on LOAD, so a dev who drops icons in and restarts gets them — but note this
      // module is cached for the session, so mid-session additions reach the manifest (its
      // middleware re-reads per request) before they reach the head.
      return renderRootRouteModule(
        config,
        routerSpecifier,
        //No favicon links on the native target. A WebView has no tab, no
        //bookmark bar and no address bar to put one in, so every link here is a
        //request nothing will ever make — and `native-bundle.ts` deletes the art
        //itself from that bundle, which would turn each of these into a 404 on
        //every cold launch.
        context.target === "capacitor"
          ? []
          : headIconLinks(
              resolveIconSet(context.appRoot, config, defaultIconFiles()),
            ),
      )
    },
  }
}

const DEFAULT_ROUTER_SPECIFIER = "@arrzdev/adaptv/router"

//router keys adaptv consumes itself — never forwarded to createRouter
const NON_CREATE_ROUTER_KEYS = new Set<string>([
  "memoryHistoryInStandalone",
  ...ROUTER_BUILD_KEYS,
])

const BANNER =
  "/* Generated by @arrzdev/adaptv from adaptv.config.ts — served as a VIRTUAL module, not written to disk. */"

/**
 * The app's root route, as a **virtual module**. → `docs/design/architecture.md §3.2`
 *
 * This used to be `.adaptv/root.gen.tsx` — a real file in every consumer's repo
 * containing `createRootRoute(<their config>)` plus static imports of their
 * splash / not-found / offline components. Almost all of it was framework code;
 * the only app-specific parts are the config values and those component
 * specifiers, both of which are known at config time.
 *
 * So it does not need to be a file. adaptv ships a real root-route module
 * (`src/routes/root-route.tsx`) that imports this virtual module for the
 * app-specific half. Nothing lands in the consumer's tree.
 *
 * ⚠︎ The component imports are still emitted **statically**. That is
 * load-bearing for `offlineComponent`: if it resolved to its own lazy chunk then
 * in the exact situation it exists for — chunks unavailable — that chunk would be
 * unavailable too, and the user would get a blank screen instead of the offline
 * screen. → `docs/design/rendering.md §3.1.2`
 */
export function renderRootRouteModule(
  config: AdaptvAppConfig,
  routerSpecifier: string = DEFAULT_ROUTER_SPECIFIER,
  iconLinks: Array<Record<string, string>> = [],
): string {
  const imports: string[] = [
    `import { createRootRoute } from ${JSON.stringify(routerSpecifier)}`,
    `import appStyles from ${JSON.stringify(`${toAppAlias(config.styles)}?url`)}`,
  ]

  //resolve a possibly-partial themeColor to concrete light + dark — a single-color
  //app uses the one provided color for both appearances (meta + launch gap).
  const theme = resolveThemeColors(config.themeColor)

  //config fields → CreateRootRouteConfig. Data values are serialized; component
  //slots reference the statically-imported defaults.
  const fields: string[] = [
    `themeColorLight: ${JSON.stringify(theme.light)}`,
    `themeColorDark: ${JSON.stringify(theme.dark)}`,
    `title: ${JSON.stringify(config.title ?? config.name)}`,
  ]
  if (config.description) {
    fields.push(`description: ${JSON.stringify(config.description)}`)
  }
  fields.push(`lang: ${JSON.stringify(config.lang ?? "en")}`)
  if (config.allowZoom !== undefined) {
    fields.push(`allowZoom: ${JSON.stringify(config.allowZoom)}`)
  }
  if (config.defaultThemePreference) {
    fields.push(
      `defaultThemePreference: ${JSON.stringify(config.defaultThemePreference)}`,
    )
  }
  if (config.patches) {
    fields.push(`patches: ${serializeValue(config.patches)}`)
  }
  //omitted when absent, so the shell applies adaptv's own `"app"` defaults rather
  //than being handed an explicit `undefined` to re-derive them from
  if (config.ui) {
    fields.push(`ui: ${serializeValue(config.ui)}`)
  }
  if (config.openGraph) {
    fields.push(`openGraph: ${serializeValue(config.openGraph)}`)
  }
  if (config.twitter)
    fields.push(`twitter: ${serializeValue(config.twitter)}`)
  //No `serviceWorker` field: registration is not configurable and not
  //conditional. The shell registers on web and standalone, and skips itself on
  //native and in dev — decisions the runtime already owns. → docs/design/rendering.md §3.4
  //The favicon / touch-icon links, resolved from the files that actually exist. Baked in
  //HERE rather than invented by `pwaHead` at runtime, because deciding them means reading the
  //icon directory and the shell has no filesystem. → `src/vite/icon-set.ts`
  if (iconLinks.length > 0)
    fields.push(`links: ${serializeValue(iconLinks)}`)
  fields.push(`stylesEntryPoint: appStyles`)

  const splash = importThunk(
    config,
    "splashScreen",
    "SplashComponent",
    imports,
  )
  if (splash) fields.push(`splashScreenComponent: ${splash}`)
  if (config.splashScreenInBrowser !== undefined) {
    fields.push(
      `splashScreenInBrowser: ${JSON.stringify(config.splashScreenInBrowser)}`,
    )
  }

  const guard = importThunk(
    config,
    "orientationGuardScreen",
    "OrientationGuardComponent",
    imports,
  )
  if (guard) fields.push(`orientationGuardComponent: ${guard}`)

  //The threshold is emitted on its own: an app that only wants adaptv's default
  //screen sets the number and no component, and one that only wants the state
  //(`useStoreRelease`) sets neither. A component with no threshold renders
  //nothing, deliberately — the number is what opts an app into taking the screen.
  if (config.updateRequiredAfterDays !== undefined) {
    fields.push(
      `updateRequiredAfterDays: ${JSON.stringify(config.updateRequiredAfterDays)}`,
    )
  }
  const updateRequired = importThunk(
    config,
    "updateRequiredScreen",
    "UpdateRequiredComponent",
    imports,
  )
  if (updateRequired) {
    fields.push(`updateRequiredComponent: ${updateRequired}`)
  }

  const notFound = importThunk(
    config,
    "notFoundScreen",
    "NotFoundComponent",
    imports,
  )
  if (notFound) fields.push(`notFoundComponent: ${notFound}`)

  //STATIC import, deliberately. If the offline UI lived in its own lazy chunk,
  //then in the exact situation it exists for — chunks unavailable — that chunk
  //would be unavailable too, and the user would get a blank screen instead of the
  //offline screen. docs/design/rendering.md §3.1.2
  const offline = importThunk(
    config,
    "offlineComponent",
    "OfflineComponent",
    imports,
  )
  if (offline) fields.push(`offlineComponent: ${offline}`)

  const configLiteral = `{\n    ${fields.join(",\n    ")},\n  }`

  return [
    BANNER,
    imports.join("\n"),
    "",
    `export const Route = createRootRoute(\n  ${configLiteral},\n)`,
    "",
  ].join("\n")
}

function importThunk(
  config: AdaptvAppConfig,
  field:
    | "splashScreen"
    | "orientationGuardScreen"
    | "updateRequiredScreen"
    | "notFoundScreen"
    | "offlineComponent",
  localName: string,
  imports: string[],
): string | null {
  const thunk = config[field]
  if (!thunk) return null
  const specifier = extractThunkSpecifier(field, thunk)
  imports.push(`import ${localName} from ${JSON.stringify(specifier)}`)
  return localName
}

/** `./src/styles/main.css` → `@/styles/main.css` (the app's own alias). */
function toAppAlias(stylesPath: string): string {
  return stylesPath.replace(/^\.\/src\//, "@/").replace(/^src\//, "@/")
}
