import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import { resolveGeneratedPaths } from "#adaptv/vite/adaptv-dir"
import {
  adaptvOpacityCheckPlugin,
  rewriteRouteTree,
  rewriteRouteTreeOnDisk,
  routeTreeMentionsTanStack,
  watchRouteTree,
} from "#adaptv/vite/route-tree-opacity"

const PKG = "@arrzdev/adaptv/router"

//What TanStack's generator writes in a consumer install (no pnpm patch reaches it).
const GENERATED = `/* eslint-disable */
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import type { CreateFileRoute } from "@tanstack/react-router"
declare module "@tanstack/react-start" {
  interface Register {}
}
`

describe("rewriteRouteTree — the tree may not name the machinery underneath", () => {
  const out = rewriteRouteTree(GENERATED, PKG)

  it("repoints the router specifier at the adaptv barrel", () => {
    expect(out).toContain(`from "${PKG}"`)
    expect(out).not.toContain("@tanstack/react-router")
  })

  it("repoints the Start `declare module` too", () => {
    //SSR adds a Register augmentation against `@tanstack/react-start`; leaving it
    //behind means typed routing is declared on a module the consumer never imports
    expect(out).not.toContain("@tanstack/react-start")
    expect(out).toContain(`declare module "${PKG}"`)
  })

  it("rewrites the generator's own attribution line", () => {
    //this is the consumer's file — it must name the tool they actually use
    expect(out).toContain("generated by adaptv.")
    expect(out).not.toContain("generated by TanStack Router.")
  })

  it("leaves an already-opaque tree completely alone", () => {
    expect(rewriteRouteTree(out, PKG)).toBe(out)
    expect(routeTreeMentionsTanStack(out)).toBe(false)
  })
})

describe("rewriteRouteTreeOnDisk", () => {
  let dir: string
  let tree: string

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
  })

  it("repairs the file in place", () => {
    rewriteRouteTreeOnDisk(tree, PKG)
    const after = readFileSync(tree, "utf8")
    expect(after).toContain(`from "${PKG}"`)
    expect(after).toContain("generated by adaptv.")
  })

  it("RESTORES mtime — the repair must not read as an outside edit", () => {
    //Not cosmetic. TanStack's generator uses mtime alone as its change signal: it
    //drops a watch event whose mtime matches its cache, and `safeFileWrite` throws
    //`rerun` when the file's mtime is not the one it last wrote. A repair that
    //bumps the mtime to "now" invites a force-rewrite of the generator's version.
    //Tolerance, not equality: `utimesSync` restores to filesystem precision and
    //drops the sub-millisecond digits — see the note on rewriteRouteTreeOnDisk.
    const before = statSync(tree).mtimeMs
    rewriteRouteTreeOnDisk(tree, PKG)
    expect(statSync(tree).mtimeMs).toBeCloseTo(before, 0)
    expect(readFileSync(tree, "utf8")).toContain(PKG) //and it really did write
  })

  it("does not write at all when the tree is already opaque", () => {
    rewriteRouteTreeOnDisk(tree, PKG)
    const settled = readFileSync(tree, "utf8")
    rewriteRouteTreeOnDisk(tree, PKG)
    expect(readFileSync(tree, "utf8")).toBe(settled)
  })

  it("is a no-op when the tree has not been generated yet", () => {
    expect(() =>
      rewriteRouteTreeOnDisk(path.join(dir, "absent.gen.ts"), PKG),
    ).not.toThrow()
  })
})

describe("adaptvOpacityCheckPlugin — every mode that can generate, repairs", () => {
  let dir: string
  let tree: string
  // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
  let plugin: any

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
    plugin = adaptvOpacityCheckPlugin(dir, PKG)
  })

  //the plugin's safety net holds OS watch handles; leaking one per test starves
  //the later ones (fs.watch starts failing, and the net silently returns null)
  afterEach(() => {
    plugin.closeWatcher()
  })

  const opaque = () =>
    !routeTreeMentionsTanStack(readFileSync(tree, "utf8"))

  it("repairs on preview start", () => {
    //THE REGRESSION: `vite preview` loads the config, so the generator runs from
    //`configResolved` and writes the tree — but preview never builds, so
    //`closeBundle` never fires. The whole time `adaptv preview` was up, the
    //consumer's file said `@tanstack/react-router`.
    plugin.configurePreviewServer()
    expect(opaque()).toBe(true)
  })

  it("repairs on dev-server start", () => {
    //same gap as preview: a dev session never reaches `closeBundle`, and dev is
    //exactly when someone opens the generated file to read it
    plugin.configureServer({ watcher: { on() {} } })
    expect(opaque()).toBe(true)
  })

  it("repairs on every write the dev watcher reports", () => {
    //dev regenerates on each route-file change, so one repair at startup is not enough
    const handlers: Array<(file: string) => void> = []
    plugin.configureServer({
      watcher: {
        on(_event: string, fn: (file: string) => void) {
          handlers.push(fn)
        },
      },
    })
    writeFileSync(tree, GENERATED) //the generator regenerating mid-session
    expect(opaque()).toBe(false)
    for (const fn of handlers) fn(tree)
    expect(opaque()).toBe(true)
  })

  it("ignores watcher events for other files", () => {
    const handlers: Array<(file: string) => void> = []
    plugin.configureServer({
      watcher: {
        on(_e: string, fn: (file: string) => void) {
          handlers.push(fn)
        },
      },
    })
    writeFileSync(tree, GENERATED)
    for (const fn of handlers)
      fn(path.join(dir, "src/routing/pages/a.page.tsx"))
    expect(opaque()).toBe(false) //untouched — only the tree's own events repair it
  })

  it("repairs at buildStart, so a build that dies early still leaves it clean", () => {
    plugin.buildStart()
    expect(opaque()).toBe(true)
  })

  it("repairs at closeBundle", () => {
    plugin.closeBundle()
    expect(opaque()).toBe(true)
  })

  it("rewrites the bundle copy too, without touching disk", () => {
    //`transform` runs per request; writing from it means writing on every reload
    const result = plugin.transform(GENERATED, tree)
    expect(result.code).toContain(PKG)
    expect(opaque()).toBe(false) //disk deliberately untouched here
  })

  it("survives the generator's write-then-rename", async () => {
    //THE reason the net watches the directory: the generator writes a temp file and
    //renames it into place, so a file-watch loses its inode on the first
    //regeneration and goes deaf — silently. Real events, real directory: this is
    //the one place event DELIVERY is exercised.
    plugin.configResolved()
    const tmp = path.join(dir, "incoming.tmp")
    writeFileSync(tmp, GENERATED)
    renameSync(tmp, tree)
    await expect.poll(opaque, { timeout: 5000 }).toBe(true)
  })

  it("stops watching when Vite closes its watcher", () => {
    plugin.configResolved()
    expect(() => plugin.closeWatcher()).not.toThrow()
    expect(() => plugin.closeWatcher()).not.toThrow() //idempotent
  })
})

describe("the safety net is armed in every mode, exactly once", () => {
  //The net is what makes "always fixed" not depend on someone having enumerated
  //Vite's lifecycle correctly — so *that it is armed* is the property to pin, and
  //it is pinned deterministically (an injected arming function) rather than
  //through real filesystem events, which race under a loaded suite.
  const armed = () => {
    const dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    const tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
    const calls: string[] = []
    // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
    const plugin: any = adaptvOpacityCheckPlugin(dir, PKG, (p) => {
      calls.push(p)
      return { close() {} }
    })
    return { plugin, calls, tree }
  }

  // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
  type Hook = [name: string, invoke: (plugin: any) => void]
  const HOOKS: Hook[] = [
    ["configResolved", (p) => p.configResolved()],
    ["buildStart", (p) => p.buildStart()],
    [
      "configureServer",
      (p) => p.configureServer({ watcher: { on() {} } }),
    ],
    ["configurePreviewServer", (p) => p.configurePreviewServer()],
  ]

  it.each(HOOKS)("%s arms it", (_name, invoke) => {
    const { plugin, calls, tree } = armed()
    invoke(plugin)
    expect(calls).toEqual([tree])
  })

  it("does not stack watchers when a mode reaches several hooks", () => {
    //a build hits configResolved AND buildStart AND closeBundle; each extra
    //watcher is an OS handle leaked for the life of the process
    const { plugin, calls } = armed()
    plugin.configResolved()
    plugin.buildStart()
    plugin.configureServer({ watcher: { on() {} } })
    plugin.configurePreviewServer()
    expect(calls).toHaveLength(1)
  })

  it("re-arms after Vite closes the watcher", () => {
    const { plugin, calls } = armed()
    plugin.configResolved()
    plugin.closeWatcher()
    plugin.buildStart()
    expect(calls).toHaveLength(2)
  })
})

describe("watchRouteTree", () => {
  it("returns null rather than throwing when the path cannot be watched", () => {
    //a safety net that fails the build is not a safety net
    expect(watchRouteTree("\0invalid/routeTree.gen.ts", () => {})).toBe(
      null,
    )
  })
})
