/**
 * Route-tree opacity — keeping `@tanstack/*` out of the one generated file adaptv
 * does not write itself. → `docs/design/architecture.md §3.2`, `src/vite/verify-patches.ts`
 *
 * Split out of `adaptv-plugin.ts` so the repair (and the lifecycle coverage that
 * decides *when* it runs) can be tested directly — the bug it exists to prevent is
 * invisible in a build and only shows up in dev and preview.
 */
import type { FSWatcher } from "node:fs"
import {
  mkdirSync,
  readFileSync,
  statSync,
  utimesSync,
  watch,
  writeFileSync,
} from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import type { PluginOption } from "vite"
import { resolveGeneratedPaths } from "#adaptv/vite/adaptv-dir.ts"
import { assertRouteTreeIsOpaque } from "#adaptv/vite/verify-patches.ts"

//The route tree is the one generated file adaptv doesn't emit itself — TanStack's
//generator writes it, hardcoding `@tanstack/react-router` (and, under SSR, the
//`@tanstack/react-start` Register declaration) into type-only imports. Those leak
//`@tanstack/*` into the consumer's TYPE surface, silently disabling the facade.
//adaptv used to fix this by patching the generator in the CONSUMER's install — but
//pnpm cannot carry a library's `patchedDependencies` downstream, so every consumer
//had to replicate them. Instead we redirect the finished tree here: the specifiers
//are all `import type` / `declare module`, so esbuild erases them — the BUNDLE is
//byte-identical — and only the type surface is repointed at the barrel. No consumer
//patch required. → src/vite/verify-patches.ts (the assertion this now satisfies).
const ROUTE_TREE_TANSTACK = /(["'])@tanstack\/react-(?:router|start)\1/g
//The generator also signs its own header ("automatically generated by TanStack Router").
//That's the consumer's file — it must say who they actually use. Same doctrine as the
//specifiers: the tool underneath is adaptv's business, not theirs.
const ROUTE_TREE_ATTRIBUTION = /generated by TanStack Router\./g
//Every import in the tree, so an adaptv module can be recognised by where it RESOLVES.
const ROUTE_TREE_RELATIVE_IMPORT = /(from\s+)(["'])(\.[^"']*)\2/g
const MODULE_EXT = /\.(?:tsx?|jsx?|m[tj]s)$/

/**
 * One of adaptv's own modules that the generated tree imports, and the specifier it
 * should be imported by instead.
 *
 * TanStack writes BOTH by relative path — `path.relative(dirname(routeTree), file)` —
 * because both are configured as file paths, which is the only thing the generator and
 * `resolveEntry` accept (the latter prepends `./` to anything that is not already
 * relative, so a bare specifier is structurally impossible there):
 *
 * - the **router entry**, in Start's route-tree footer, type-only
 * - the **root route**, reached through the virtual-route DSL, a VALUE import
 *
 * For a module inside the package that path is computed from a realpath, so it comes out
 * install-shaped: `../../../../src/routes/root-route` against a workspace link, and
 * `../node_modules/.pnpm/@arrzdev+adaptv@0.1.0_<peerhash>/node_modules/@arrzdev/adaptv/…`
 * in a real install. It is regenerated per run, so it is never *stale* — but it encodes
 * the machine's node_modules layout, has no answer under an install that keeps nothing
 * on disk (Yarn PnP), and dies on a dist-only publish, where `src/` is gone and
 * `resolveEntry` is `required: true`.
 */
export type RouteTreeModule = {
  /** Absolute path of the module inside adaptv. */
  file: string
  /** The specifier the tree should name it by. */
  specifier: string
}

/** Path with any module extension removed, so `./x` and `./x.tsx` compare equal. */
function withoutExt(file: string): string {
  return file.replace(MODULE_EXT, "")
}

/**
 * adaptv's own modules the generated tree points at, keyed off the router specifier so
 * an aliased install (`routerSpecifier`) stays internally consistent.
 *
 * Both are real files in the package — never generated into the consumer's tree — and
 * both are reachable by name through `package.json` `exports`, which is what makes the
 * rewrite below resolve to the SAME module the relative path did.
 */
export function adaptvRouteTreeModules(
  routerPkg: string,
): RouteTreeModule[] {
  return [
    {
      //typed through the barrel's `export type { getRouter }`, so the tree's
      //`Register` augmentation and its `getRouter` name one identical module
      file: fileURLToPath(
        new URL("../routes/router-entry.tsx", import.meta.url),
      ),
      specifier: routerPkg,
    },
    {
      //a value import: same package, sibling subpath. Derived from `routerPkg` rather
      //than hardcoded so an aliased install rewrites to a specifier it can resolve.
      file: fileURLToPath(
        new URL("../routes/root-route.tsx", import.meta.url),
      ),
      specifier: routerPkg.replace(/\/[^/]+$/, "/root-route"),
    },
  ]
}

/** Repoint a generated route tree at adaptv — the `@tanstack/*` specifiers, the paths
 * reaching into adaptv's install directory, and the generator's own attribution line.
 * One function so every call site (bundle + disk) stays in step; a rewrite applied in
 * only one of them is how the leak comes back.
 *
 * Imports are matched by WHERE THEY RESOLVE, not by the local name the generator gave
 * them. That is what makes ejection work without a flag: an app that writes its own
 * `src/router.tsx` or root layout keeps a relative import to a file in its own tree,
 * which matches nothing here and is left exactly as generated — repointing it at adaptv
 * would bind `Register` to a `getRouter` that is not theirs. It also means a renamed
 * upstream binding cannot silently disable the rewrite. */
export function rewriteRouteTree(
  source: string,
  routerPkg: string,
  own: {
    routeTreePath: string
    modules: readonly RouteTreeModule[]
  } | null = null,
): string {
  const out = source
    .replace(ROUTE_TREE_TANSTACK, `$1${routerPkg}$1`)
    .replace(ROUTE_TREE_ATTRIBUTION, "generated by adaptv.")
  if (!own || own.modules.length === 0) return out

  const dir = path.dirname(own.routeTreePath)
  const byPath = new Map(
    own.modules.map((m) => [
      withoutExt(path.resolve(m.file)),
      m.specifier,
    ]),
  )
  return out.replace(
    ROUTE_TREE_RELATIVE_IMPORT,
    (match, from: string, quote: string, specifier: string) => {
      const hit = byPath.get(withoutExt(path.resolve(dir, specifier)))
      return hit ? `${from}${quote}${hit}${quote}` : match
    },
  )
}

/**
 * Relative imports in the tree that reach into an install directory — the property that
 * actually matters, checked instead of the one rewrite known to cause it.
 *
 * The route tree is FULL of legitimate relative imports (every route file, and the app's
 * own `src/router.tsx` when the router is ejected). Relative is not the fault. Reaching
 * a file whose location is decided by a package manager is.
 *
 * Two shapes, because adaptv is reached two different ways and only one of them leaves
 * the app:
 *
 * - **Outside the app root.** A workspace link or `pnpm link` realpaths to wherever the
 *   framework is checked out — `../../../../src/routes/router-entry.tsx` in this repo.
 * - **Through `node_modules`.** A normal install resolves INSIDE the app —
 *   `../node_modules/.pnpm/@arrzdev+adaptv@0.1.0_<peerhash>/…` — so a root check alone
 *   would wave through the exact case every consumer actually has. (Found by a test
 *   written against the first rule; it is the more important of the two.)
 *
 * Deliberately not keyed on `getRouter`: if upstream renames that binding, or adds a
 * second footer import of the same shape (`startFilePath` already emits one when an app
 * has a start entry), a `getRouter`-shaped check would pass while the leak returned.
 * This is the invariant; the rewrite above is just today's mechanism for holding it.
 */
export function findUnportableImports(
  source: string,
  routeTreePath: string,
  appRoot: string,
): string[] {
  const dir = path.dirname(routeTreePath)
  const root = path.resolve(appRoot)
  const found: string[] = []
  for (const [, , specifier] of source.matchAll(
    /\bfrom\s+(["'])(\.[^"']*)\1/g,
  )) {
    const resolved = path.resolve(dir, specifier)
    const inApp = resolved === root || resolved.startsWith(root + path.sep)
    const viaNodeModules = resolved
      .split(path.sep)
      .includes("node_modules")
    if (inApp && !viaNodeModules) continue
    found.push(specifier)
  }
  return found
}

/**
 * Fail the build when the generated tree still reaches into an install directory.
 *
 * Same doctrine as `assertRouteTreeIsOpaque`: the alternative is a SILENT revert.
 * Upstream owns the footer text, so a reworded template would slip past the rewrite
 * and the build would keep succeeding — with a route tree whose type layer only
 * resolves on the machine that generated it. → src/vite/verify-patches.ts
 */
export function assertRouteTreeIsPortable(
  routeTreePath: string,
  appRoot: string,
): void {
  let source: string
  try {
    source = readFileSync(routeTreePath, "utf8")
  } catch {
    return //not generated yet on this pass — nothing to assert
  }
  const unportable = findUnportableImports(source, routeTreePath, appRoot)
  if (unportable.length === 0) return

  throw new Error(
    [
      "[adaptv] The generated route tree imports adaptv by file path, not by name:",
      `  ${routeTreePath}`,
      ...unportable.map((s) => `    ${s}`),
      "",
      "Those paths are recomputed on every run, so they work on the machine that wrote",
      "them — and nowhere else. They encode this exact node_modules layout (pnpm's store",
      "hash and peer-dependency hash included), resolve to nothing under an install that",
      "keeps no node_modules on disk, and disappear entirely if adaptv ships built output",
      "instead of `src/`.",
      "",
      "adaptv rewrites those imports to package specifiers after the generator runs, by",
      "matching where each one RESOLVES. If you are seeing this, a module adaptv points",
      "the generator at is not in that list — add it to `adaptvRouteTreeModules` in",
      "src/vite/route-tree-opacity.ts, with a `package.json` export to reach it by.",
    ].join("\n"),
  )
}

/** Does this tree still mention the machinery underneath? Cheap pre-check before rewriting. */
export function routeTreeMentionsTanStack(source: string): boolean {
  return /@tanstack\/react-|generated by TanStack Router\./.test(source)
}

/**
 * Repair the tree ON DISK, putting the clock back on the way out.
 *
 * ⚠︎ The `utimesSync` is not tidiness. TanStack's generator uses **mtime alone** as
 * its change signal, in two places: it drops a watch event whose mtime matches its
 * cache, and `safeFileWrite` throws `rerun` when the file's mtime is not the one it
 * last wrote. An external write that bumps the mtime therefore reads as "someone
 * edited my output" and invites a force-rewrite of the generator's own version —
 * which we would repair, which it would rewrite. Restoring the timestamp keeps the
 * repair from looking like an outside edit.
 *
 * Two honest limits, neither of which is load-bearing:
 *
 * 1. `utimesSync` restores to filesystem precision, not exactly (sub-millisecond
 *    digits are lost), so this NARROWS the window rather than closing it.
 * 2. It is defence in depth, not the reason the loop is absent. **Measured** with
 *    a live dev server: after the repair the file holds a single (mtime, content)
 *    state across 40 samples over 12s, and seeding the generator's own text back
 *    onto disk three times converges every time, with no reload and no `rerun` in
 *    the log. Vite's dev server does not drive the generator from this file's
 *    events the way a build watcher would.
 *
 * The trade is that an mtime-based incremental tool (a warm `tsc --build`) can miss
 * the repair. Acceptable: the content difference is type-only.
 */
export function rewriteRouteTreeOnDisk(
  routeTreePath: string,
  routerPkg: string,
  modules: readonly RouteTreeModule[] = [],
): void {
  let source: string
  let stamp: { atime: Date; mtime: Date }
  try {
    source = readFileSync(routeTreePath, "utf8")
    const stat = statSync(routeTreePath)
    stamp = { atime: stat.atime, mtime: stat.mtime }
  } catch {
    return //not generated on this pass — nothing to rewrite
  }
  const rewritten = rewriteRouteTree(source, routerPkg, {
    routeTreePath,
    modules,
  })
  if (rewritten === source) return
  writeFileSync(routeTreePath, rewritten)
  try {
    utimesSync(routeTreePath, stamp.atime, stamp.mtime)
  } catch {
    //worst case the generator re-runs once — the repair itself already landed
  }
}

/**
 * Watch the generated tree for the life of the process and repair every write.
 *
 * The hooks below cover the modes that exist today — but "the repair runs in build
 * and nowhere else" is exactly the bug this file was just fixed for, and that bug
 * came from trusting an enumeration of Vite's lifecycle. This is the net underneath
 * it: whatever writes `@tanstack/*` into that file, in whatever mode, at whatever
 * point, it is repaired within milliseconds without anyone having to have predicted
 * the code path.
 *
 * ⚠︎ Watches the **directory and the file**, because neither alone is enough —
 * measured on macOS, not assumed:
 *
 * - The generator writes to a temp path and `rename()`s it into place. That
 *   discards the inode a file-watch is holding, so a file-only watch goes deaf
 *   after the first regeneration — silently, the worst failure for a safety net.
 *   Hence the directory watch, and hence re-arming the file watch after every
 *   directory event (the file it was holding is gone).
 * - A directory watch does not report an in-place write to a file already in it.
 *   Today the generator always renames, so this only matters if a future version
 *   writes in place — which is exactly the kind of silent regression a net is for.
 *
 * Both are `unref()`d, so they never keep a build process alive.
 */
export function watchRouteTree(
  routeTreePath: string,
  repair: () => void,
): { close: () => void } | null {
  const dir = path.dirname(routeTreePath)
  const base = path.basename(routeTreePath)
  let fileWatcher: FSWatcher | null = null

  const armFile = () => {
    fileWatcher?.close()
    fileWatcher = null
    try {
      fileWatcher = watch(routeTreePath, () => repair())
      fileWatcher.unref()
    } catch {
      //not generated yet — the directory watch will re-arm us when it appears
    }
  }

  try {
    //`.adaptv/` is adaptv's own directory; the generator creates it too
    mkdirSync(dir, { recursive: true })
    const dirWatcher = watch(dir, (_event, filename) => {
      //`filename` is null on some platforms — repair anyway, it is a guarded read
      if (filename && path.basename(filename) !== base) return
      repair()
      armFile() //a rename replaced the file: the old inode is dead
    })
    dirWatcher.unref()
    armFile()
    return {
      close() {
        dirWatcher.close()
        fileWatcher?.close()
        fileWatcher = null
      },
    }
  } catch {
    //a net, not the mechanism — an unwatchable fs must not fail the build
    return null
  }
}

/**
 * Redirects the generated route tree's outward-facing type imports at adaptv's barrel
 * — the `@tanstack/*` specifiers and the router entry's install-shaped relative path —
 * in the bundle (`transform`) and on disk (so tsc, the IDE, and the checks see the
 * facade), then asserts both invariants.
 *
 * ## Why the repair is hooked into every Vite mode, not just the build
 *
 * The generator runs from `configResolved`, which fires in **dev, preview and
 * build alike**. `closeBundle` fires only in a build. So for a long time the
 * on-disk tree was correct after `adaptv build` and named TanStack for the entire
 * lifetime of `adaptv dev` and `adaptv preview` — and dev is exactly when someone
 * opens `.adaptv/routeTree.gen.ts` and reads it. The bundle was always right; the
 * file the consumer actually looks at was not.
 *
 * So the repair now runs wherever a generation can happen: `buildStart` (also
 * covers a build that dies before `closeBundle`), server start plus every write
 * the watcher reports (dev regenerates on each route change), preview start, and
 * `closeBundle` as before.
 *
 * ## Why this is a repair at all, rather than generating the right text
 *
 * Every upstream lever for emitting the correct text is closed to a consumer:
 * `routeTreeFileHeader` only *prepends* (the "generated by TanStack Router" line
 * is appended after it), the router specifier is hardcoded in the target template,
 * and the generator's `plugins` array — the one hook that could rewrite the
 * content before it is written — is **overwritten** by Start, which hardcodes its
 * own list. adaptv's `pnpm patch` closes all of this, but pnpm cannot carry a
 * library's `patchedDependencies` into a consumer's install. Hence: repair.
 */
export function adaptvOpacityCheckPlugin(
  appRoot: string,
  routerPkg: string,
  //adaptv's own modules the tree may name by path. Injected rather than derived here so
  //a test can drive the rewrite without owning real files. → adaptvRouteTreeModules
  modules: readonly RouteTreeModule[] = adaptvRouteTreeModules(routerPkg),
  //Seam, and the only reason this argument exists: "the net is armed in EVERY
  //mode" is the property that matters, and asserting it through real filesystem
  //events makes the test a race — it passed alone and failed under a loaded
  //suite. Injecting the arming function lets that be checked deterministically;
  //event delivery itself is covered separately against a real directory.
  arm: typeof watchRouteTree = watchRouteTree,
): PluginOption {
  const routeTree = resolveGeneratedPaths(appRoot).routeTree
  const repair = () =>
    rewriteRouteTreeOnDisk(routeTree, routerPkg, modules)
  const verify = () => {
    assertRouteTreeIsOpaque(routeTree)
    assertRouteTreeIsPortable(routeTree, appRoot)
  }

  //One watcher per plugin instance, opened by whichever hook runs first. Every
  //Vite mode reaches at least one of them, so the net is always up — and it is
  //idempotent, because a mode that reaches several must not open several.
  let watcher: { close: () => void } | null = null
  const net = () => {
    if (!watcher) watcher = arm(routeTree, repair)
  }

  return {
    name: "adaptv:route-tree-opacity",
    enforce: "pre",
    //Fires in dev, build AND preview — the earliest common point, so the net is up
    //before the generator's first write in any mode.
    configResolved() {
      net()
      //deliberately no repair here: `configResolved` hooks run concurrently, so
      //the generator's write may not have landed yet. The watcher covers it.
    },
    transform(code, id) {
      if (path.resolve(id) !== path.resolve(routeTree)) return null
      //Compare the OUTPUT rather than pre-checking for `@tanstack` — the entry-path
      //rewrite has nothing to do with TanStack specifiers, and a tree needing only
      //that one would have been skipped by a `routeTreeMentionsTanStack` guard.
      const rewritten = rewriteRouteTree(code, routerPkg, {
        routeTreePath: routeTree,
        modules,
      })
      if (rewritten === code) return null
      //Bundle only — deliberately NOT written to disk here. `transform` runs per
      //request, so writing from it means writing on every reload; the disk copy is
      //repaired by the lifecycle hooks below, which run once per generation.
      return { code: rewritten, map: null }
    },
    buildStart() {
      net()
      repair()
    },
    configureServer(server) {
      //`configResolved` (where the generator writes) has already completed by now.
      net()
      repair()
      verify()
      //dev regenerates on every route-file change. The repair is content-guarded,
      //so the event our own write raises is a no-op and this cannot ping-pong.
      const onWrite = (file: string) => {
        if (path.resolve(file) === path.resolve(routeTree)) repair()
      }
      server.watcher.on("add", onWrite)
      server.watcher.on("change", onWrite)
    },
    configurePreviewServer() {
      //Preview never builds, so `closeBundle` never fires — this used to be the
      //one mode that left `@tanstack/*` sitting in the consumer's file.
      net()
      repair()
      verify()
    },
    closeBundle() {
      //belt-and-suspenders: catch anything transform didn't reach, then verify.
      repair()
      verify()
    },
    closeWatcher() {
      //Vite is shutting its watcher down — ours has nothing left to protect.
      watcher?.close()
      watcher = null
    },
  }
}
