/**
 * Route-tree opacity — keeping `@tanstack/*` out of the one generated file adaptv
 * does not write itself. → `ARCHITECTURE.md §3.2`, `src/vite/verify-patches.ts`
 *
 * Split out of `adaptv-plugin.ts` so the repair (and the lifecycle coverage that
 * decides *when* it runs) can be tested directly — the bug it exists to prevent is
 * invisible in a build and only shows up in dev and preview.
 */
import type { FSWatcher } from "node:fs"
import {
  mkdirSync,
  readFileSync,
  statSync,
  utimesSync,
  watch,
  writeFileSync,
} from "node:fs"
import path from "node:path"
import type { PluginOption } from "vite"
import { resolveGeneratedPaths } from "#adaptv/vite/adaptv-dir.ts"
import { assertRouteTreeIsOpaque } from "#adaptv/vite/verify-patches.ts"

//The route tree is the one generated file adaptv doesn't emit itself — TanStack's
//generator writes it, hardcoding `@tanstack/react-router` (and, under SSR, the
//`@tanstack/react-start` Register declaration) into type-only imports. Those leak
//`@tanstack/*` into the consumer's TYPE surface, silently disabling the facade.
//adaptv used to fix this by patching the generator in the CONSUMER's install — but
//pnpm cannot carry a library's `patchedDependencies` downstream, so every consumer
//had to replicate them. Instead we redirect the finished tree here: the specifiers
//are all `import type` / `declare module`, so esbuild erases them — the BUNDLE is
//byte-identical — and only the type surface is repointed at the barrel. No consumer
//patch required. → src/vite/verify-patches.ts (the assertion this now satisfies).
const ROUTE_TREE_TANSTACK = /(["'])@tanstack\/react-(?:router|start)\1/g
//The generator also signs its own header ("automatically generated by TanStack Router").
//That's the consumer's file — it must say who they actually use. Same doctrine as the
//specifiers: the tool underneath is adaptv's business, not theirs.
const ROUTE_TREE_ATTRIBUTION = /generated by TanStack Router\./g

/** Repoint a generated route tree at adaptv — both the `@tanstack/*` specifiers and the
 * generator's own attribution line. One function so every call site (bundle + disk) stays
 * in step; a rewrite applied in only one of them is how `@tanstack` leaks back. */
export function rewriteRouteTree(
  source: string,
  routerPkg: string,
): string {
  return source
    .replace(ROUTE_TREE_TANSTACK, `$1${routerPkg}$1`)
    .replace(ROUTE_TREE_ATTRIBUTION, "generated by adaptv.")
}

/** Does this tree still mention the machinery underneath? Cheap pre-check before rewriting. */
export function routeTreeMentionsTanStack(source: string): boolean {
  return /@tanstack\/react-|generated by TanStack Router\./.test(source)
}

/**
 * Repair the tree ON DISK, putting the clock back on the way out.
 *
 * ⚠︎ The `utimesSync` is not tidiness. TanStack's generator uses **mtime alone** as
 * its change signal, in two places: it drops a watch event whose mtime matches its
 * cache, and `safeFileWrite` throws `rerun` when the file's mtime is not the one it
 * last wrote. An external write that bumps the mtime therefore reads as "someone
 * edited my output" and invites a force-rewrite of the generator's own version —
 * which we would repair, which it would rewrite. Restoring the timestamp keeps the
 * repair from looking like an outside edit.
 *
 * Two honest limits, neither of which is load-bearing:
 *
 * 1. `utimesSync` restores to filesystem precision, not exactly (sub-millisecond
 *    digits are lost), so this NARROWS the window rather than closing it.
 * 2. It is defence in depth, not the reason the loop is absent. **Measured** with
 *    a live dev server: after the repair the file holds a single (mtime, content)
 *    state across 40 samples over 12s, and seeding the generator's own text back
 *    onto disk three times converges every time, with no reload and no `rerun` in
 *    the log. Vite's dev server does not drive the generator from this file's
 *    events the way a build watcher would.
 *
 * The trade is that an mtime-based incremental tool (a warm `tsc --build`) can miss
 * the repair. Acceptable: the content difference is type-only.
 */
export function rewriteRouteTreeOnDisk(
  routeTreePath: string,
  routerPkg: string,
): void {
  let source: string
  let stamp: { atime: Date; mtime: Date }
  try {
    source = readFileSync(routeTreePath, "utf8")
    const stat = statSync(routeTreePath)
    stamp = { atime: stat.atime, mtime: stat.mtime }
  } catch {
    return //not generated on this pass — nothing to rewrite
  }
  const rewritten = rewriteRouteTree(source, routerPkg)
  if (rewritten === source) return
  writeFileSync(routeTreePath, rewritten)
  try {
    utimesSync(routeTreePath, stamp.atime, stamp.mtime)
  } catch {
    //worst case the generator re-runs once — the repair itself already landed
  }
}

/**
 * Watch the generated tree for the life of the process and repair every write.
 *
 * The hooks below cover the modes that exist today — but "the repair runs in build
 * and nowhere else" is exactly the bug this file was just fixed for, and that bug
 * came from trusting an enumeration of Vite's lifecycle. This is the net underneath
 * it: whatever writes `@tanstack/*` into that file, in whatever mode, at whatever
 * point, it is repaired within milliseconds without anyone having to have predicted
 * the code path.
 *
 * ⚠︎ Watches the **directory and the file**, because neither alone is enough —
 * measured on macOS, not assumed:
 *
 * - The generator writes to a temp path and `rename()`s it into place. That
 *   discards the inode a file-watch is holding, so a file-only watch goes deaf
 *   after the first regeneration — silently, the worst failure for a safety net.
 *   Hence the directory watch, and hence re-arming the file watch after every
 *   directory event (the file it was holding is gone).
 * - A directory watch does not report an in-place write to a file already in it.
 *   Today the generator always renames, so this only matters if a future version
 *   writes in place — which is exactly the kind of silent regression a net is for.
 *
 * Both are `unref()`d, so they never keep a build process alive.
 */
export function watchRouteTree(
  routeTreePath: string,
  repair: () => void,
): { close: () => void } | null {
  const dir = path.dirname(routeTreePath)
  const base = path.basename(routeTreePath)
  let fileWatcher: FSWatcher | null = null

  const armFile = () => {
    fileWatcher?.close()
    fileWatcher = null
    try {
      fileWatcher = watch(routeTreePath, () => repair())
      fileWatcher.unref()
    } catch {
      //not generated yet — the directory watch will re-arm us when it appears
    }
  }

  try {
    //`.adaptv/` is adaptv's own directory; the generator creates it too
    mkdirSync(dir, { recursive: true })
    const dirWatcher = watch(dir, (_event, filename) => {
      //`filename` is null on some platforms — repair anyway, it is a guarded read
      if (filename && path.basename(filename) !== base) return
      repair()
      armFile() //a rename replaced the file: the old inode is dead
    })
    dirWatcher.unref()
    armFile()
    return {
      close() {
        dirWatcher.close()
        fileWatcher?.close()
        fileWatcher = null
      },
    }
  } catch {
    //a net, not the mechanism — an unwatchable fs must not fail the build
    return null
  }
}

/**
 * Redirects the generated route tree's `@tanstack/*` type imports at adaptv's barrel
 * — in the bundle (`transform`) and on disk (so tsc, the IDE, and the opacity check
 * see the facade) — then asserts the invariant.
 *
 * ## Why the repair is hooked into every Vite mode, not just the build
 *
 * The generator runs from `configResolved`, which fires in **dev, preview and
 * build alike**. `closeBundle` fires only in a build. So for a long time the
 * on-disk tree was correct after `adaptv build` and named TanStack for the entire
 * lifetime of `adaptv dev` and `adaptv preview` — and dev is exactly when someone
 * opens `.adaptv/routeTree.gen.ts` and reads it. The bundle was always right; the
 * file the consumer actually looks at was not.
 *
 * So the repair now runs wherever a generation can happen: `buildStart` (also
 * covers a build that dies before `closeBundle`), server start plus every write
 * the watcher reports (dev regenerates on each route change), preview start, and
 * `closeBundle` as before.
 *
 * ## Why this is a repair at all, rather than generating the right text
 *
 * Every upstream lever for emitting the correct text is closed to a consumer:
 * `routeTreeFileHeader` only *prepends* (the "generated by TanStack Router" line
 * is appended after it), the router specifier is hardcoded in the target template,
 * and the generator's `plugins` array — the one hook that could rewrite the
 * content before it is written — is **overwritten** by Start, which hardcodes its
 * own list. adaptv's `pnpm patch` closes all of this, but pnpm cannot carry a
 * library's `patchedDependencies` into a consumer's install. Hence: repair.
 */
export function adaptvOpacityCheckPlugin(
  appRoot: string,
  routerPkg: string,
  //Seam, and the only reason this argument exists: "the net is armed in EVERY
  //mode" is the property that matters, and asserting it through real filesystem
  //events makes the test a race — it passed alone and failed under a loaded
  //suite. Injecting the arming function lets that be checked deterministically;
  //event delivery itself is covered separately against a real directory.
  arm: typeof watchRouteTree = watchRouteTree,
): PluginOption {
  const routeTree = resolveGeneratedPaths(appRoot).routeTree
  const repair = () => rewriteRouteTreeOnDisk(routeTree, routerPkg)

  //One watcher per plugin instance, opened by whichever hook runs first. Every
  //Vite mode reaches at least one of them, so the net is always up — and it is
  //idempotent, because a mode that reaches several must not open several.
  let watcher: { close: () => void } | null = null
  const net = () => {
    if (!watcher) watcher = arm(routeTree, repair)
  }

  return {
    name: "adaptv:route-tree-opacity",
    enforce: "pre",
    //Fires in dev, build AND preview — the earliest common point, so the net is up
    //before the generator's first write in any mode.
    configResolved() {
      net()
      //deliberately no repair here: `configResolved` hooks run concurrently, so
      //the generator's write may not have landed yet. The watcher covers it.
    },
    transform(code, id) {
      if (path.resolve(id) !== path.resolve(routeTree)) return null
      if (!routeTreeMentionsTanStack(code)) return null
      //Bundle only — deliberately NOT written to disk here. `transform` runs per
      //request, so writing from it means writing on every reload; the disk copy is
      //repaired by the lifecycle hooks below, which run once per generation.
      return { code: rewriteRouteTree(code, routerPkg), map: null }
    },
    buildStart() {
      net()
      repair()
    },
    configureServer(server) {
      //`configResolved` (where the generator writes) has already completed by now.
      net()
      repair()
      assertRouteTreeIsOpaque(routeTree)
      //dev regenerates on every route-file change. The repair is content-guarded,
      //so the event our own write raises is a no-op and this cannot ping-pong.
      const onWrite = (file: string) => {
        if (path.resolve(file) === path.resolve(routeTree)) repair()
      }
      server.watcher.on("add", onWrite)
      server.watcher.on("change", onWrite)
    },
    configurePreviewServer() {
      //Preview never builds, so `closeBundle` never fires — this used to be the
      //one mode that left `@tanstack/*` sitting in the consumer's file.
      net()
      repair()
      assertRouteTreeIsOpaque(routeTree)
    },
    closeBundle() {
      //belt-and-suspenders: catch anything transform didn't reach, then verify.
      repair()
      assertRouteTreeIsOpaque(routeTree)
    },
    closeWatcher() {
      //Vite is shutting its watcher down — ours has nothing left to protect.
      watcher?.close()
      watcher = null
    },
  }
}
