import { EventEmitter } from "node:events"
import {
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import { resolveGeneratedPaths } from "#adaptv/vite/adaptv-dir"
import {
  adaptvOpacityCheckPlugin,
  findUnportableImports,
  ignoreUnchangedRouteTree,
  rewriteRouteTree,
  rewriteRouteTreeOnDisk,
  routeTreeMentionsTanStack,
  watchRouteTree,
} from "#adaptv/vite/route-tree-opacity"

const PKG = "@arrzdev/adaptv/router"

//The app whose tree is being generated. `/app/.adaptv/routeTree.gen.ts` is where the
//generator writes, so every relative specifier below resolves from `/app/.adaptv`.
const APP = "/app"
const TREE = "/app/.adaptv/routeTree.gen.ts"
const ROOT_ROUTE_PKG = "@arrzdev/adaptv/root-route"

//Where adaptv lands in a REAL pnpm install: inside the app root, behind the store's
//version+peer hash. Nothing about that path is stable across machines — which is the
//whole point. The relative specifiers in the tree are the same whatever the app root
//is, so only the absolute module paths are parameterised.
const INSTALL_REL =
  "node_modules/.pnpm/@arrzdev+adaptv@0.1.0_react@19.2.3/node_modules/@arrzdev/adaptv"
const modulesIn = (root: string) => [
  {
    file: path.join(root, INSTALL_REL, "src/routes/router-entry.tsx"),
    specifier: PKG,
  },
  {
    file: path.join(root, INSTALL_REL, "src/routes/root-route.tsx"),
    specifier: ROOT_ROUTE_PKG,
  },
]
const own = (modules = modulesIn(APP)) => ({
  routeTreePath: TREE,
  modules,
})

//What TanStack's generator writes in a consumer install (no pnpm patch reaches it).
//Three relative imports, and only one of them is legitimate: the app's own route file.
//The other two reach into adaptv's install — the root route as a VALUE import, the
//router entry type-only in Start's footer.
const GENERATED = `/* eslint-disable */
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import type { CreateFileRoute } from "@tanstack/react-router"
import { Route as rootRouteImport } from "./../node_modules/.pnpm/@arrzdev+adaptv@0.1.0_react@19.2.3/node_modules/@arrzdev/adaptv/src/routes/root-route"
import { Route as HomeRoute } from "../src/routing/pages/home.page"
declare module "@tanstack/react-start" {
  interface Register {}
}
import type { getRouter } from "../node_modules/.pnpm/@arrzdev+adaptv@0.1.0_react@19.2.3/node_modules/@arrzdev/adaptv/src/routes/router-entry.tsx"
`

//The same tree after the repair. Used as an INERT watch stimulus: renaming it
//into place raises a real filesystem event while leaving nothing to repair.
const OPAQUE = rewriteRouteTree(GENERATED, PKG)

describe("rewriteRouteTree — the tree may not name the machinery underneath", () => {
  const out = rewriteRouteTree(GENERATED, PKG)

  it("repoints the router specifier at the adaptv barrel", () => {
    expect(out).toContain(`from "${PKG}"`)
    expect(out).not.toContain("@tanstack/react-router")
  })

  it("repoints the Start `declare module` too", () => {
    //SSR adds a Register augmentation against `@tanstack/react-start`; leaving it
    //behind means typed routing is declared on a module the consumer never imports
    expect(out).not.toContain("@tanstack/react-start")
    expect(out).toContain(`declare module "${PKG}"`)
  })

  it("rewrites the generator's own attribution line", () => {
    //this is the consumer's file — it must name the tool they actually use
    expect(out).toContain("generated by adaptv.")
    expect(out).not.toContain("generated by TanStack Router.")
  })

  it("leaves an already-opaque tree completely alone", () => {
    expect(rewriteRouteTree(out, PKG)).toBe(out)
    expect(routeTreeMentionsTanStack(out)).toBe(false)
  })
})

describe("rewriteRouteTree — adaptv is named, never located", () => {
  const out = rewriteRouteTree(GENERATED, PKG, own())

  it("repoints the footer's router-entry import at the package specifier", () => {
    //upstream writes `path.relative(dirname(routeTree), routerFilePath)`, which for
    //adaptv's own entry lands in the install directory — correct only on the machine
    //that generated it, and absent entirely under PnP or a dist-only publish
    expect(out).toContain(`import type { getRouter } from "${PKG}"`)
  })

  it("repoints the root route too — a VALUE import, so this one is runtime", () => {
    //the type-only footer erases; this does not. Under a dist publish the relative
    //path resolves to a `.tsx` that was never shipped, and the app fails to build.
    expect(out).toContain(
      `import { Route as rootRouteImport } from "${ROOT_ROUTE_PKG}"`,
    )
  })

  it("leaves nothing pointing into the install directory", () => {
    expect(out).not.toContain("node_modules")
  })

  it("names the same module the Register augmentation is declared on", () => {
    //split them and `Register` augments one module while `getRouter` is typed through
    //another: typed routing goes dead with nothing to show for it
    expect(out).toContain(`declare module "${PKG}"`)
  })

  it("leaves the app's own route imports alone", () => {
    //relative is not the problem — REACHING INTO AN INSTALL is. Every route file in
    //the tree is a relative import and must survive verbatim.
    expect(out).toContain('from "../src/routing/pages/home.page"')
  })

  it("leaves an ejected entry alone, with no flag to say so", () => {
    //Matching on WHERE AN IMPORT RESOLVES is what makes this free: an app that writes
    //its own `src/router.tsx` or root layout keeps a path into its own tree, which is
    //in nobody's module list. Repointing it would bind `Register` to adaptv's
    //`getRouter` instead of theirs — typed routing dead, no error.
    const ejected = `import type { getRouter } from "../src/router.tsx"`
    expect(rewriteRouteTree(ejected, PKG, own())).toBe(ejected)
  })

  it("matches regardless of the local name the generator chose", () => {
    //keyed on resolution, not on `rootRouteImport`/`getRouter`, so a renamed upstream
    //binding cannot silently switch the rewrite off
    const renamed = `import { Route as somethingElse } from "./../node_modules/.pnpm/@arrzdev+adaptv@0.1.0_react@19.2.3/node_modules/@arrzdev/adaptv/src/routes/root-route"`
    expect(rewriteRouteTree(renamed, PKG, own())).toContain(ROOT_ROUTE_PKG)
  })

  it("is idempotent", () => {
    expect(rewriteRouteTree(out, PKG, own())).toBe(out)
  })
})

describe("findUnportableImports — the invariant, not the mechanism", () => {
  const tree = "/app/.adaptv/routeTree.gen.ts"

  it("flags a relative import that climbs out of the app", () => {
    const src = `import type { getRouter } from "../../../../src/routes/router-entry.tsx"`
    expect(findUnportableImports(src, tree, "/app")).toEqual([
      "../../../../src/routes/router-entry.tsx",
    ])
  })

  it("flags the pnpm store path a real consumer install produces", () => {
    const spec =
      "../node_modules/.pnpm/@arrzdev+adaptv@0.1.0_react@19.2.3/node_modules/@arrzdev/adaptv/src/routes/router-entry.tsx"
    expect(
      findUnportableImports(
        `import type { x } from "${spec}"`,
        tree,
        "/app",
      ),
    ).toEqual([spec])
  })

  it("accepts relative imports that stay inside the app", () => {
    const src = [
      `import { Route as A } from "../src/routing/pages/a.page"`,
      `import { Route as B } from "./nested/b"`,
      //an ejected router lives in the consumer's own tree — portable, leave it
      `import type { getRouter } from "../src/router.tsx"`,
    ].join("\n")
    expect(findUnportableImports(src, tree, "/app")).toEqual([])
  })

  it("ignores bare package specifiers", () => {
    //`@arrzdev/adaptv/router` is the goal state, not a violation
    const src = `import type { getRouter } from "@arrzdev/adaptv/router"`
    expect(findUnportableImports(src, tree, "/app")).toEqual([])
  })

  it("catches a footer import the rewrite does not know about", () => {
    //Start emits a second one (`startInstance`) when an app has a start entry, and
    //upstream may reword the template at any time. The check is keyed on the property
    //rather than on `getRouter`, so neither slips through.
    const src = `import type { startInstance } from "../../adaptv/src/start.tsx"`
    expect(findUnportableImports(src, tree, "/app")).toHaveLength(1)
  })
})

describe("rewriteRouteTreeOnDisk", () => {
  let dir: string
  let tree: string

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
  })

  it("repairs the file in place", () => {
    rewriteRouteTreeOnDisk(tree, PKG)
    const after = readFileSync(tree, "utf8")
    expect(after).toContain(`from "${PKG}"`)
    expect(after).toContain("generated by adaptv.")
  })

  it("RESTORES mtime — the repair must not read as an outside edit", () => {
    //Not cosmetic. TanStack's generator uses mtime alone as its change signal: it
    //drops a watch event whose mtime matches its cache, and `safeFileWrite` throws
    //`rerun` when the file's mtime is not the one it last wrote. A repair that
    //bumps the mtime to "now" invites a force-rewrite of the generator's version.
    //Within a microsecond, not equal: `utimesSync` takes seconds as a double, a
    //quarter of a microsecond at today's epoch. A stamp through `Date` drops the
    //sub-millisecond digits, misses by hundreds of microseconds, and so never equals
    //the `mtimeMs` the generator compares — see the note on rewriteRouteTreeOnDisk.
    const before = statSync(tree, { bigint: true }).mtimeNs
    rewriteRouteTreeOnDisk(tree, PKG)
    const drift = statSync(tree, { bigint: true }).mtimeNs - before
    expect(drift < 0n ? -drift : drift).toBeLessThan(1000n)
    expect(readFileSync(tree, "utf8")).toContain(PKG) //and it really did write
  })

  it("replaces the tree by rename, so no reader ever sees half of it", () => {
    //Every dev server in the checkout reads this file as soon as it changes. An
    //in-place write truncates first: with two servers up, one caught the tree at
    //24567 of 50031 bytes and its SSR transform died on a parse error. A new inode
    //is the observable proof the old file was swapped whole, not rewritten.
    const before = statSync(tree).ino
    rewriteRouteTreeOnDisk(tree, PKG)
    expect(statSync(tree).ino).not.toBe(before)
    expect(readdirSync(path.dirname(tree))).toEqual([path.basename(tree)])
  })

  it("never renames a stale repair over a newer generation", () => {
    //A repair reads generation N, and before its rename lands the generator renames
    //N+1 into place — in dev, the tree with a route that was just added. Renaming
    //N's rewrite over it, with N's mtime put back on it, would drop that route until
    //the next route change. The repair must stand down: N+1's own rename is a new
    //watcher event, and the repair that event runs reads N+1.
    const newer = GENERATED.replace(
      "/* eslint-disable */",
      "/* eslint-disable */\n// a route added since the repair read the tree",
    )
    expect(newer).not.toBe(GENERATED)
    rewriteRouteTreeOnDisk(tree, PKG, [], () => {
      const incoming = path.join(dir, "incoming.tmp")
      writeFileSync(incoming, newer)
      renameSync(incoming, tree)
    })
    expect(readFileSync(tree, "utf8")).toBe(newer)
    expect(readdirSync(path.dirname(tree))).toEqual([path.basename(tree)])
  })

  it("does not write at all when the tree is already opaque", () => {
    rewriteRouteTreeOnDisk(tree, PKG)
    const settled = readFileSync(tree, "utf8")
    rewriteRouteTreeOnDisk(tree, PKG)
    expect(readFileSync(tree, "utf8")).toBe(settled)
  })

  it("is a no-op when the tree has not been generated yet", () => {
    expect(() =>
      rewriteRouteTreeOnDisk(path.join(dir, "absent.gen.ts"), PKG),
    ).not.toThrow()
  })
})

describe("adaptvOpacityCheckPlugin — every mode that can generate, repairs", () => {
  let dir: string
  let tree: string
  // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
  let plugin: any

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
    plugin = adaptvOpacityCheckPlugin(dir, PKG, modulesIn(dir))
  })

  //the plugin's safety net holds OS watch handles; leaking one per test starves
  //the later ones (fs.watch starts failing, and the net silently returns null)
  afterEach(() => {
    plugin.closeWatcher()
  })

  const opaque = () =>
    !routeTreeMentionsTanStack(readFileSync(tree, "utf8"))

  it("repairs on preview start", () => {
    //THE REGRESSION: `vite preview` loads the config, so the generator runs from
    //`configResolved` and writes the tree — but preview never builds, so
    //`closeBundle` never fires. The whole time `adaptv preview` was up, the
    //consumer's file said `@tanstack/react-router`.
    plugin.configurePreviewServer()
    expect(opaque()).toBe(true)
  })

  it("repairs on dev-server start", () => {
    //same gap as preview: a dev session never reaches `closeBundle`, and dev is
    //exactly when someone opens the generated file to read it
    plugin.configureServer({ watcher: { on() {}, emit: () => false } })
    expect(opaque()).toBe(true)
  })

  it("repairs on every write the dev watcher reports", () => {
    //dev regenerates on each route-file change, so one repair at startup is not enough
    const handlers: Array<(file: string) => void> = []
    plugin.configureServer({
      watcher: {
        on(_event: string, fn: (file: string) => void) {
          handlers.push(fn)
        },
        emit: () => false,
      },
    })
    writeFileSync(tree, GENERATED) //the generator regenerating mid-session
    expect(opaque()).toBe(false)
    for (const fn of handlers) fn(tree)
    expect(opaque()).toBe(true)
  })

  it("ignores watcher events for other files", () => {
    const handlers: Array<(file: string) => void> = []
    plugin.configureServer({
      watcher: {
        on(_e: string, fn: (file: string) => void) {
          handlers.push(fn)
        },
        emit: () => false,
      },
    })
    writeFileSync(tree, GENERATED)
    for (const fn of handlers)
      fn(path.join(dir, "src/routing/pages/a.page.tsx"))
    expect(opaque()).toBe(false) //untouched — only the tree's own events repair it
  })

  it("does not hand an identical regeneration to the rest of the dev server", () => {
    //the plugin path, end to end over a real emitter: another server boots in this
    //checkout and its generator renames the same tree over this one. The baseline
    //must be the REPAIRED tree, or that raw rewrite would read as a change.
    const vite = new EventEmitter()
    const heard: string[] = []
    vite.on("change", (file: string) => heard.push(file))
    plugin.configureServer({ watcher: vite })
    writeFileSync(tree, GENERATED)
    vite.emit("change", tree)
    expect(heard).toEqual([])
  })

  it("repairs at buildStart, so a build that dies early still leaves it clean", () => {
    plugin.buildStart()
    expect(opaque()).toBe(true)
  })

  it("repairs at closeBundle", () => {
    plugin.closeBundle()
    expect(opaque()).toBe(true)
  })

  it("fails the build when adaptv points the generator at a module the rewrite does not cover", () => {
    //THE silent revert this net exists for, and it is not hypothetical: the root route
    //was in exactly this state — a second module handed to the generator by path, which
    //nobody noticed until the assertion caught it on a real build. A tree that keeps one
    //of these still BUILDS; it just only resolves on the machine that wrote it.
    writeFileSync(
      tree,
      `${GENERATED}\nimport { clientEntry } from "./../${INSTALL_REL}/src/routes/client-entry.tsx"\n`,
    )
    expect(() => plugin.closeBundle()).toThrow(
      /imports adaptv by file path, not by name/,
    )
  })

  it("rewrites the bundle copy too, without touching disk", () => {
    //`transform` runs per request; writing from it means writing on every reload
    const result = plugin.transform(GENERATED, tree)
    expect(result.code).toContain(PKG)
    expect(opaque()).toBe(false) //disk deliberately untouched here
  })

  //write-then-rename survival lives in `describe("watchRouteTree")` below: it
  //needs the repair callback as an observable signal, which the plugin does not
  //expose (it builds its own). Arming from each hook is covered above.

  it("stops watching when Vite closes its watcher", () => {
    plugin.configResolved()
    expect(() => plugin.closeWatcher()).not.toThrow()
    expect(() => plugin.closeWatcher()).not.toThrow() //idempotent
  })
})

describe("ignoreUnchangedRouteTree — a rewrite that changes nothing is not an event", () => {
  //The bug: every dev-server boot makes the generator rename its tree over the
  //repaired one. Once repaired it is byte-identical, but any OTHER dev server in
  //the checkout saw a change — its HMR sent `full-reload` to every page it served,
  //and its generator force-rewrote the file, which the booting server's generator
  //then did too. The watcher here is a real EventEmitter, standing in for Vite's
  //chokidar: its listeners are what HMR and the generator's `watchChange` hang off.
  let dir: string
  let tree: string
  let watcher: EventEmitter
  let heard: string[]

  //a real regeneration: a route the previous tree did not have
  const WITH_ROUTE = `${GENERATED}import { Route as AboutRoute } from "../src/routing/pages/about.page"\n`

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, OPAQUE) //what a dev server leaves on disk after its repair
    watcher = new EventEmitter()
    heard = []
    for (const event of ["add", "change", "unlink"])
      watcher.on(event, (file: string) => heard.push(`${event} ${file}`))
    ignoreUnchangedRouteTree(watcher, tree, (source) =>
      rewriteRouteTree(source, PKG),
    )
  })

  it("swallows the generator's raw rewrite of the tree already on disk", () => {
    //THE boot of a second server: TanStack-shaped text, identical once repaired
    writeFileSync(tree, GENERATED)
    watcher.emit("change", tree)
    expect(heard).toEqual([])
  })

  it("swallows the repaired copy renamed back over it", () => {
    writeFileSync(tree, OPAQUE)
    watcher.emit("change", tree)
    watcher.emit("add", tree)
    expect(heard).toEqual([])
  })

  it("lets a real regeneration through, exactly once", () => {
    writeFileSync(tree, WITH_ROUTE)
    watcher.emit("change", tree)
    //the repair of that same regeneration is not a second change
    writeFileSync(tree, rewriteRouteTree(WITH_ROUTE, PKG))
    watcher.emit("change", tree)
    expect(heard).toEqual([`change ${tree}`])
  })

  it("lets a change BACK through — the baseline moves with what passed", () => {
    writeFileSync(tree, WITH_ROUTE)
    watcher.emit("change", tree)
    writeFileSync(tree, GENERATED) //the route removed again
    watcher.emit("change", tree)
    expect(heard).toEqual([`change ${tree}`, `change ${tree}`])
  })

  it("announces a tree that is deleted and regenerated, even identical", () => {
    rmSync(tree)
    watcher.emit("unlink", tree)
    writeFileSync(tree, OPAQUE)
    watcher.emit("add", tree)
    expect(heard).toEqual([`unlink ${tree}`, `add ${tree}`])
  })

  it("never touches another file's events", () => {
    const page = path.join(dir, "src/routing/pages/a.page.tsx")
    watcher.emit("change", page)
    watcher.emit("change", page)
    expect(heard).toEqual([`change ${page}`, `change ${page}`])
  })
})

describe("the safety net is armed in every mode, exactly once", () => {
  //The net is what makes "always fixed" not depend on someone having enumerated
  //Vite's lifecycle correctly — so *that it is armed* is the property to pin, and
  //it is pinned deterministically (an injected arming function) rather than
  //through real filesystem events, which race under a loaded suite.
  const armed = () => {
    const dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    const tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
    const calls: string[] = []
    // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
    const plugin: any = adaptvOpacityCheckPlugin(
      dir,
      PKG,
      modulesIn(dir),
      (p) => {
        calls.push(p)
        return { close() {} }
      },
    )
    return { plugin, calls, tree }
  }

  // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
  type Hook = [name: string, invoke: (plugin: any) => void]
  const HOOKS: Hook[] = [
    ["configResolved", (p) => p.configResolved()],
    ["buildStart", (p) => p.buildStart()],
    [
      "configureServer",
      (p) =>
        p.configureServer({ watcher: { on() {}, emit: () => false } }),
    ],
    ["configurePreviewServer", (p) => p.configurePreviewServer()],
  ]

  it.each(HOOKS)("%s arms it", (_name, invoke) => {
    const { plugin, calls, tree } = armed()
    invoke(plugin)
    expect(calls).toEqual([tree])
  })

  it("does not stack watchers when a mode reaches several hooks", () => {
    //a build hits configResolved AND buildStart AND closeBundle; each extra
    //watcher is an OS handle leaked for the life of the process
    const { plugin, calls } = armed()
    plugin.configResolved()
    plugin.buildStart()
    plugin.configureServer({ watcher: { on() {}, emit: () => false } })
    plugin.configurePreviewServer()
    expect(calls).toHaveLength(1)
  })

  it("re-arms after Vite closes the watcher", () => {
    const { plugin, calls } = armed()
    plugin.configResolved()
    plugin.closeWatcher()
    plugin.buildStart()
    expect(calls).toHaveLength(2)
  })
})

describe("watchRouteTree", () => {
  it("returns null rather than throwing when the path cannot be watched", () => {
    //a safety net that fails the build is not a safety net
    expect(watchRouteTree("\0invalid/routeTree.gen.ts", () => {})).toBe(
      null,
    )
  })

  it("survives the generator's write-then-rename", async () => {
    //THE reason the net watches the directory: the generator writes a temp file
    //and renames it into place, so a file-watch loses its inode on the first
    //regeneration and goes deaf — silently. Real events, real directory: this is
    //the one place event DELIVERY is exercised, and it is written against
    //`watchRouteTree` rather than the plugin because the repair callback is the
    //only observable proof that the OS is delivering — which the barrier below
    //needs. (That the plugin arms the net at all is pinned separately, by
    //injection.)
    const dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    const tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    //seeded already-opaque, so the readiness probe has nothing to repair
    writeFileSync(tree, OPAQUE)

    let delivered = 0
    const watcher = watchRouteTree(tree, () => {
      delivered++
      rewriteRouteTreeOnDisk(tree, PKG)
    })
    expect(watcher).not.toBe(null)

    let n = 0
    //a sibling temp file renamed over the tree — what the generator does
    const renameOnto = (content: string) => {
      const tmp = path.join(dir, `incoming-${++n}.tmp`)
      writeFileSync(tmp, content)
      renameSync(tmp, tree)
    }
    const opaque = () =>
      !routeTreeMentionsTanStack(readFileSync(tree, "utf8"))
    const settle = async (ms: number) => {
      const until = Date.now() + ms
      while (delivered === 0 && Date.now() < until)
        await new Promise((r) => setTimeout(r, 5))
    }

    try {
      //⚠︎ `fs.watch` returns BEFORE the OS watch under it is live: on macOS libuv
      //creates the FSEventStream on its own thread, starting from
      //`kFSEventStreamEventIdSinceNow`, so anything that happens in the meantime
      //is never reported at all. Idle, that window is sub-millisecond and a
      //rename issued on the very next line is seen; under the full suite (113
      //files over 14 cores) it is wide enough to swallow it, and this test then
      //burned its entire timeout waiting for an event that was never coming.
      //Measured with the suite running: 1 loss in 80 renames issued immediately
      //after arming, versus 0 in 400 issued once a single event had been
      //delivered. So establish delivery with the inert stimulus first — this is
      //a readiness barrier, not a retry of the assertion — and only then perform
      //the one rename the assertion is about.
      for (let i = 0; delivered === 0; i++) {
        expect(i, "fs.watch never delivered an event").toBeLessThan(50)
        renameOnto(OPAQUE)
        await settle(100)
      }
      expect(opaque()).toBe(true) //the probe really was inert

      //the property, exercised exactly once: the rename discards the inode the
      //file watch was holding, and the tree is repaired regardless
      const before = delivered
      renameOnto(GENERATED)
      await expect.poll(opaque, { timeout: 5000 }).toBe(true)
      expect(delivered).toBeGreaterThan(before) //via a real event, not by luck
    } finally {
      watcher?.close()
    }
  })
})
