import path from "node:path"
import type { Plugin, ViteDevServer } from "vite"
import type { RouteTint } from "#adaptv/shell/route-tints.ts"
import { collectRouteTints } from "#adaptv/vite/route-tints.ts"

export const ROUTE_TINTS_VIRTUAL_ID = "virtual:adaptv/route-tints"
const RESOLVED_ROUTE_TINTS_ID = `\0${ROUTE_TINTS_VIRTUAL_ID}`

/**
 * Where adaptv's route files live, as an absolute path.
 *
 * `router.routesDirectory` is resolved against `src/`, not the app root — the
 * same base the router entry and the generated tree use, measured against Start
 * (see `adaptv-plugin.ts`). Getting this base wrong yields an empty scan and a
 * table with no entries, which is indistinguishable from an app that declares no
 * tints: silent, and wrong on the one frame it matters. One function, so there is
 * one place to be right.
 */
export function resolveRoutesDir(
  appRoot: string,
  routesDirectory: string | undefined,
): string {
  return path.resolve(appRoot, "src", routesDirectory ?? "./routing")
}

/** The module's source — a frozen table, nothing computed at runtime. */
export function renderRouteTintsModule(
  tints: readonly RouteTint[],
): string {
  return `/* Generated by adaptv — served as a VIRTUAL module, not written to disk. */
export const ROUTE_TINTS = ${JSON.stringify(tints, null, 2)}
`
}

/**
 * Serve `virtual:adaptv/route-tints` — the build-time route→chrome-tint table.
 * → `src/shell/route-tints.ts`
 *
 * Both consumers of the table import it from here rather than computing their
 * own: the generated root route, which inlines it into the pre-paint script, and
 * the shell, which keeps the tint current across navigations. One table means the
 * colour painted before hydration and the colour maintained after it cannot
 * disagree — and a route whose tint this scan cannot read fails the BUILD rather
 * than diverging between the two.
 *
 * Re-scanned when a route file changes, because the alternative in dev is editing
 * `chromeTint` and watching nothing happen until a restart.
 */
export function adaptvRouteTintsPlugin(routesDir: string): Plugin {
  let server: ViteDevServer | null = null
  return {
    name: "adaptv:route-tints",
    configureServer(dev) {
      server = dev
    },
    resolveId(id) {
      if (id === ROUTE_TINTS_VIRTUAL_ID) return RESOLVED_ROUTE_TINTS_ID
      return null
    },
    load(id) {
      if (id !== RESOLVED_ROUTE_TINTS_ID) return null
      return renderRouteTintsModule(collectRouteTints(routesDir))
    },
    //`hotUpdate`, with the server captured above rather than taken from the
    //hook's options — the environment-aware hook does not hand one over, and the
    //table is server-wide anyway (it is the same table in every environment).
    hotUpdate({ file }) {
      if (!server || !file.startsWith(routesDir + path.sep)) return
      const mod = server.moduleGraph.getModuleById(RESOLVED_ROUTE_TINTS_ID)
      if (mod) server.moduleGraph.invalidateModule(mod)
    },
  }
}
