import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  statSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import path from "node:path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"
import { resolveGeneratedPaths } from "#adaptv/vite/adaptv-dir"
import {
  adaptvOpacityCheckPlugin,
  rewriteRouteTree,
  rewriteRouteTreeOnDisk,
  routeTreeMentionsTanStack,
  watchRouteTree,
} from "#adaptv/vite/route-tree-opacity"

const PKG = "@arrzdev/adaptv/router"

//What TanStack's generator writes in a consumer install (no pnpm patch reaches it).
const GENERATED = `/* eslint-disable */
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import type { CreateFileRoute } from "@tanstack/react-router"
declare module "@tanstack/react-start" {
  interface Register {}
}
`

//The same tree after the repair. Used as an INERT watch stimulus: renaming it
//into place raises a real filesystem event while leaving nothing to repair.
const OPAQUE = rewriteRouteTree(GENERATED, PKG)

describe("rewriteRouteTree — the tree may not name the machinery underneath", () => {
  const out = rewriteRouteTree(GENERATED, PKG)

  it("repoints the router specifier at the adaptv barrel", () => {
    expect(out).toContain(`from "${PKG}"`)
    expect(out).not.toContain("@tanstack/react-router")
  })

  it("repoints the Start `declare module` too", () => {
    //SSR adds a Register augmentation against `@tanstack/react-start`; leaving it
    //behind means typed routing is declared on a module the consumer never imports
    expect(out).not.toContain("@tanstack/react-start")
    expect(out).toContain(`declare module "${PKG}"`)
  })

  it("rewrites the generator's own attribution line", () => {
    //this is the consumer's file — it must name the tool they actually use
    expect(out).toContain("generated by adaptv.")
    expect(out).not.toContain("generated by TanStack Router.")
  })

  it("leaves an already-opaque tree completely alone", () => {
    expect(rewriteRouteTree(out, PKG)).toBe(out)
    expect(routeTreeMentionsTanStack(out)).toBe(false)
  })
})

describe("rewriteRouteTreeOnDisk", () => {
  let dir: string
  let tree: string

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
  })

  it("repairs the file in place", () => {
    rewriteRouteTreeOnDisk(tree, PKG)
    const after = readFileSync(tree, "utf8")
    expect(after).toContain(`from "${PKG}"`)
    expect(after).toContain("generated by adaptv.")
  })

  it("RESTORES mtime — the repair must not read as an outside edit", () => {
    //Not cosmetic. TanStack's generator uses mtime alone as its change signal: it
    //drops a watch event whose mtime matches its cache, and `safeFileWrite` throws
    //`rerun` when the file's mtime is not the one it last wrote. A repair that
    //bumps the mtime to "now" invites a force-rewrite of the generator's version.
    //Tolerance, not equality: `utimesSync` restores to filesystem precision and
    //drops the sub-millisecond digits — see the note on rewriteRouteTreeOnDisk.
    const before = statSync(tree).mtimeMs
    rewriteRouteTreeOnDisk(tree, PKG)
    expect(statSync(tree).mtimeMs).toBeCloseTo(before, 0)
    expect(readFileSync(tree, "utf8")).toContain(PKG) //and it really did write
  })

  it("does not write at all when the tree is already opaque", () => {
    rewriteRouteTreeOnDisk(tree, PKG)
    const settled = readFileSync(tree, "utf8")
    rewriteRouteTreeOnDisk(tree, PKG)
    expect(readFileSync(tree, "utf8")).toBe(settled)
  })

  it("is a no-op when the tree has not been generated yet", () => {
    expect(() =>
      rewriteRouteTreeOnDisk(path.join(dir, "absent.gen.ts"), PKG),
    ).not.toThrow()
  })
})

describe("adaptvOpacityCheckPlugin — every mode that can generate, repairs", () => {
  let dir: string
  let tree: string
  // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
  let plugin: any

  beforeEach(() => {
    dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
    plugin = adaptvOpacityCheckPlugin(dir, PKG)
  })

  //the plugin's safety net holds OS watch handles; leaking one per test starves
  //the later ones (fs.watch starts failing, and the net silently returns null)
  afterEach(() => {
    plugin.closeWatcher()
  })

  const opaque = () =>
    !routeTreeMentionsTanStack(readFileSync(tree, "utf8"))

  it("repairs on preview start", () => {
    //THE REGRESSION: `vite preview` loads the config, so the generator runs from
    //`configResolved` and writes the tree — but preview never builds, so
    //`closeBundle` never fires. The whole time `adaptv preview` was up, the
    //consumer's file said `@tanstack/react-router`.
    plugin.configurePreviewServer()
    expect(opaque()).toBe(true)
  })

  it("repairs on dev-server start", () => {
    //same gap as preview: a dev session never reaches `closeBundle`, and dev is
    //exactly when someone opens the generated file to read it
    plugin.configureServer({ watcher: { on() {} } })
    expect(opaque()).toBe(true)
  })

  it("repairs on every write the dev watcher reports", () => {
    //dev regenerates on each route-file change, so one repair at startup is not enough
    const handlers: Array<(file: string) => void> = []
    plugin.configureServer({
      watcher: {
        on(_event: string, fn: (file: string) => void) {
          handlers.push(fn)
        },
      },
    })
    writeFileSync(tree, GENERATED) //the generator regenerating mid-session
    expect(opaque()).toBe(false)
    for (const fn of handlers) fn(tree)
    expect(opaque()).toBe(true)
  })

  it("ignores watcher events for other files", () => {
    const handlers: Array<(file: string) => void> = []
    plugin.configureServer({
      watcher: {
        on(_e: string, fn: (file: string) => void) {
          handlers.push(fn)
        },
      },
    })
    writeFileSync(tree, GENERATED)
    for (const fn of handlers)
      fn(path.join(dir, "src/routing/pages/a.page.tsx"))
    expect(opaque()).toBe(false) //untouched — only the tree's own events repair it
  })

  it("repairs at buildStart, so a build that dies early still leaves it clean", () => {
    plugin.buildStart()
    expect(opaque()).toBe(true)
  })

  it("repairs at closeBundle", () => {
    plugin.closeBundle()
    expect(opaque()).toBe(true)
  })

  it("rewrites the bundle copy too, without touching disk", () => {
    //`transform` runs per request; writing from it means writing on every reload
    const result = plugin.transform(GENERATED, tree)
    expect(result.code).toContain(PKG)
    expect(opaque()).toBe(false) //disk deliberately untouched here
  })

  //write-then-rename survival lives in `describe("watchRouteTree")` below: it
  //needs the repair callback as an observable signal, which the plugin does not
  //expose (it builds its own). Arming from each hook is covered above.

  it("stops watching when Vite closes its watcher", () => {
    plugin.configResolved()
    expect(() => plugin.closeWatcher()).not.toThrow()
    expect(() => plugin.closeWatcher()).not.toThrow() //idempotent
  })
})

describe("the safety net is armed in every mode, exactly once", () => {
  //The net is what makes "always fixed" not depend on someone having enumerated
  //Vite's lifecycle correctly — so *that it is armed* is the property to pin, and
  //it is pinned deterministically (an injected arming function) rather than
  //through real filesystem events, which race under a loaded suite.
  const armed = () => {
    const dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    const tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    writeFileSync(tree, GENERATED)
    const calls: string[] = []
    // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
    const plugin: any = adaptvOpacityCheckPlugin(dir, PKG, (p) => {
      calls.push(p)
      return { close() {} }
    })
    return { plugin, calls, tree }
  }

  // biome-ignore lint/suspicious/noExplicitAny: exercising Vite hooks directly
  type Hook = [name: string, invoke: (plugin: any) => void]
  const HOOKS: Hook[] = [
    ["configResolved", (p) => p.configResolved()],
    ["buildStart", (p) => p.buildStart()],
    [
      "configureServer",
      (p) => p.configureServer({ watcher: { on() {} } }),
    ],
    ["configurePreviewServer", (p) => p.configurePreviewServer()],
  ]

  it.each(HOOKS)("%s arms it", (_name, invoke) => {
    const { plugin, calls, tree } = armed()
    invoke(plugin)
    expect(calls).toEqual([tree])
  })

  it("does not stack watchers when a mode reaches several hooks", () => {
    //a build hits configResolved AND buildStart AND closeBundle; each extra
    //watcher is an OS handle leaked for the life of the process
    const { plugin, calls } = armed()
    plugin.configResolved()
    plugin.buildStart()
    plugin.configureServer({ watcher: { on() {} } })
    plugin.configurePreviewServer()
    expect(calls).toHaveLength(1)
  })

  it("re-arms after Vite closes the watcher", () => {
    const { plugin, calls } = armed()
    plugin.configResolved()
    plugin.closeWatcher()
    plugin.buildStart()
    expect(calls).toHaveLength(2)
  })
})

describe("watchRouteTree", () => {
  it("returns null rather than throwing when the path cannot be watched", () => {
    //a safety net that fails the build is not a safety net
    expect(watchRouteTree("\0invalid/routeTree.gen.ts", () => {})).toBe(
      null,
    )
  })

  it("survives the generator's write-then-rename", async () => {
    //THE reason the net watches the directory: the generator writes a temp file
    //and renames it into place, so a file-watch loses its inode on the first
    //regeneration and goes deaf — silently. Real events, real directory: this is
    //the one place event DELIVERY is exercised, and it is written against
    //`watchRouteTree` rather than the plugin because the repair callback is the
    //only observable proof that the OS is delivering — which the barrier below
    //needs. (That the plugin arms the net at all is pinned separately, by
    //injection.)
    const dir = mkdtempSync(path.join(tmpdir(), "adaptv-opacity-"))
    const tree = resolveGeneratedPaths(dir).routeTree
    mkdirSync(path.dirname(tree), { recursive: true })
    //seeded already-opaque, so the readiness probe has nothing to repair
    writeFileSync(tree, OPAQUE)

    let delivered = 0
    const watcher = watchRouteTree(tree, () => {
      delivered++
      rewriteRouteTreeOnDisk(tree, PKG)
    })
    expect(watcher).not.toBe(null)

    let n = 0
    //a sibling temp file renamed over the tree — what the generator does
    const renameOnto = (content: string) => {
      const tmp = path.join(dir, `incoming-${++n}.tmp`)
      writeFileSync(tmp, content)
      renameSync(tmp, tree)
    }
    const opaque = () =>
      !routeTreeMentionsTanStack(readFileSync(tree, "utf8"))
    const settle = async (ms: number) => {
      const until = Date.now() + ms
      while (delivered === 0 && Date.now() < until)
        await new Promise((r) => setTimeout(r, 5))
    }

    try {
      //⚠︎ `fs.watch` returns BEFORE the OS watch under it is live: on macOS libuv
      //creates the FSEventStream on its own thread, starting from
      //`kFSEventStreamEventIdSinceNow`, so anything that happens in the meantime
      //is never reported at all. Idle, that window is sub-millisecond and a
      //rename issued on the very next line is seen; under the full suite (113
      //files over 14 cores) it is wide enough to swallow it, and this test then
      //burned its entire timeout waiting for an event that was never coming.
      //Measured with the suite running: 1 loss in 80 renames issued immediately
      //after arming, versus 0 in 400 issued once a single event had been
      //delivered. So establish delivery with the inert stimulus first — this is
      //a readiness barrier, not a retry of the assertion — and only then perform
      //the one rename the assertion is about.
      for (let i = 0; delivered === 0; i++) {
        expect(i, "fs.watch never delivered an event").toBeLessThan(50)
        renameOnto(OPAQUE)
        await settle(100)
      }
      expect(opaque()).toBe(true) //the probe really was inert

      //the property, exercised exactly once: the rename discards the inode the
      //file watch was holding, and the tree is repaired regardless
      const before = delivered
      renameOnto(GENERATED)
      await expect.poll(opaque, { timeout: 5000 }).toBe(true)
      expect(delivered).toBeGreaterThan(before) //via a real event, not by luck
    } finally {
      watcher?.close()
    }
  })
})
