import type { Plugin } from "vite"
import { pluginDir } from "#adaptv/native/installed-plugins.ts"
import type { AdaptvContext } from "#adaptv/vite/adaptv-context.ts"

/**
 * `virtual:adaptv/secure-storage` — the Keychain/KeyStore backend, if the app has
 * one. → `src/storage/secure.ts`
 *
 * ## The problem this solves, and why the obvious shape does not
 *
 * The backend is an **optional** peer: a web-only app must not be made to install
 * a Keychain plugin, and `tsc` must not fail for one that hasn't. The obvious way
 * to get both is to hide the specifier from the compiler —
 * `import(/* @vite-ignore *\/ SOME_CONST)` — and that is what this replaces.
 *
 * It does hide it from `tsc`. It also hides it from **Rollup**, which is not
 * optional: a specifier the bundler cannot see is emitted verbatim, so the shipped
 * native bundle asked the WebView to resolve a bare
 * `@aparajita/capacitor-secure-storage`. WebViews have no import map, so that
 * import always rejected — *including for consumers who had installed the
 * package*. `storage.secure` therefore reported "install it and run `adaptv
 * sync`" to people who had done exactly that, which is worse than a plain
 * failure: it sends the one person who could fix it to fix something that was
 * already right.
 *
 * A virtual module gets both properties honestly. The consumer's source imports a
 * fixed id that always resolves, and the decision about whether the real package
 * exists is made HERE, at build time, where the filesystem can answer it. When it
 * does exist the emitted module is a **static re-export** — a literal specifier
 * Rollup follows and bundles.
 */

export const SECURE_STORAGE_VIRTUAL_ID = "virtual:adaptv/secure-storage"
const RESOLVED_SECURE_STORAGE_ID = `\0${SECURE_STORAGE_VIRTUAL_ID}`

/** The backend adaptv supports. MIT; Keychain on iOS, AndroidKeyStore on Android. */
export const SECURE_STORAGE_PACKAGE = "@aparajita/capacitor-secure-storage"

/**
 * The virtual module's source.
 *
 * ⚠︎ The installed branch must stay a **static re-export of a literal**. A dynamic
 * import, a computed specifier, or a `@vite-ignore` anywhere in it puts the
 * specifier back out of Rollup's reach and restores the original bug in a form
 * that still type-checks and still builds.
 */
export function renderSecureStorageModule(installed: boolean): string {
  const banner =
    "/* Generated by @arrzdev/adaptv — served as a VIRTUAL module, not written to disk. */"
  if (!installed) {
    //`null`, not a throw: the call sites turn this into one clear, actionable
    //error, and only on the platform where it actually matters
    return `${banner}\nexport const SecureStorage = null\n`
  }
  return `${banner}\nexport { SecureStorage } from ${JSON.stringify(
    SECURE_STORAGE_PACKAGE,
  )}\n`
}

/** Whether the app (or adaptv) can actually resolve the backend. */
export function hasSecureStorage(
  appRoot: string,
  adaptvRoot?: string,
): boolean {
  return pluginDir(SECURE_STORAGE_PACKAGE, appRoot, adaptvRoot) !== null
}

/** Serve `virtual:adaptv/secure-storage`. */
export function adaptvSecureStoragePlugin(context: AdaptvContext): Plugin {
  return {
    name: "adaptv:secure-storage",
    resolveId(id) {
      if (id === SECURE_STORAGE_VIRTUAL_ID)
        return RESOLVED_SECURE_STORAGE_ID
      return null
    },
    load(id) {
      if (id !== RESOLVED_SECURE_STORAGE_ID) return null
      return renderSecureStorageModule(hasSecureStorage(context.appRoot))
    },
  }
}
