import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs"
import path from "node:path"
import type { NativAppConfig } from "#nativ/config/app-config.ts"
import {
  ROUTER_BUILD_KEYS,
  resolveThemeColors,
} from "#nativ/config/app-config.ts"
import type { NativContext } from "#nativ/vite/nativ-context.ts"
import { serializeValue } from "#nativ/vite/serialize.ts"
import { extractThunkSpecifier } from "#nativ/vite/thunk-specifiers.ts"

//generated route files, relative to the app's src dir. Gitignored, stamped on
//every config load — the app author never writes these.
const ROOT_GEN_REL = "routing/layouts/__root.gen.tsx"
const ROUTER_GEN_REL = "router.gen.tsx"

//an app can eject either file by writing the real one; nativ then defers.
const ROOT_EJECT_REL = "routing/layouts/_root.tsx"
const ROUTER_EJECT_REL = "router.tsx"

const BANNER =
  "/* Generated by @repo/nativ from nativ.config.ts. Do not edit — your changes will be overwritten. */"

export type EjectState = {
  root: boolean
  router: boolean
}

/**
 * Stamp the generated root + router files from the loaded config, unless the app
 * has ejected by writing the real file. Runs in the `nativ()` factory so both
 * files exist before TanStack Start resolves `router.entry` and the route
 * generator reads the virtual route config. (The client entry is Start's default;
 * nativ generates nothing for it.)
 */
export function stampGeneratedFiles(context: NativContext): EjectState {
  if (!context.loaded) return { root: false, router: false }
  const { config } = context.loaded
  const srcDir = path.resolve(context.appRoot, "src")

  const rootEjected = existsSync(path.resolve(srcDir, ROOT_EJECT_REL))
  const routerEjected = existsSync(path.resolve(srcDir, ROUTER_EJECT_REL))

  if (!rootEjected) {
    writeIfChanged(
      path.resolve(srcDir, ROOT_GEN_REL),
      renderRootGen(config),
    )
  }
  if (!routerEjected) {
    writeIfChanged(
      path.resolve(srcDir, ROUTER_GEN_REL),
      renderRouterGen(config),
    )
  }

  return { root: rootEjected, router: routerEjected }
}

/* =============================================================================
 * ROOT
 * ============================================================================= */

function renderRootGen(config: NativAppConfig): string {
  const imports: string[] = [
    `import { createRootRoute } from "@repo/nativ/shell"`,
    `import appStyles from ${JSON.stringify(`${toAppAlias(config.styles)}?url`)}`,
  ]

  //resolve a possibly-partial themeColor to concrete light + dark — a single-color
  //app uses the one provided color for both appearances (meta + launch gap).
  const theme = resolveThemeColors(config.themeColor)

  //config fields → CreateRootRouteConfig. Data values are serialized; component
  //slots reference the statically-imported defaults.
  const fields: string[] = [
    `themeColorLight: ${JSON.stringify(theme.light)}`,
    `themeColorDark: ${JSON.stringify(theme.dark)}`,
    `title: ${JSON.stringify(config.title ?? config.name)}`,
  ]
  if (config.description) {
    fields.push(`description: ${JSON.stringify(config.description)}`)
  }
  fields.push(`lang: ${JSON.stringify(config.lang ?? "en")}`)
  if (config.allowZoom !== undefined) {
    fields.push(`allowZoom: ${JSON.stringify(config.allowZoom)}`)
  }
  if (config.defaultThemePreference) {
    fields.push(
      `defaultThemePreference: ${JSON.stringify(config.defaultThemePreference)}`,
    )
  }
  if (config.patches) {
    fields.push(`patches: ${serializeValue(config.patches)}`)
  }
  if (config.openGraph) {
    fields.push(`openGraph: ${serializeValue(config.openGraph)}`)
  }
  if (config.twitter)
    fields.push(`twitter: ${serializeValue(config.twitter)}`)
  if (config.sw !== false)
    fields.push(`serviceWorker: { register: "autoUpdate" }`)
  fields.push(`stylesEntryPoint: appStyles`)

  const splash = importThunk(
    config,
    "splashScreen",
    "SplashComponent",
    imports,
  )
  if (splash) fields.push(`splashScreenComponent: ${splash}`)
  if (config.splashScreenInBrowser !== undefined) {
    fields.push(
      `splashScreenInBrowser: ${JSON.stringify(config.splashScreenInBrowser)}`,
    )
  }

  const guard = importThunk(
    config,
    "orientationGuardScreen",
    "OrientationGuardComponent",
    imports,
  )
  if (guard) fields.push(`orientationGuardComponent: ${guard}`)

  const notFound = importThunk(
    config,
    "notFoundScreen",
    "NotFoundComponent",
    imports,
  )
  if (notFound) fields.push(`notFoundComponent: ${notFound}`)

  const providers = importThunk(
    config,
    "providers",
    "AppProviders",
    imports,
  )

  const configLiteral = `{\n    ${fields.join(",\n    ")},\n  }`
  const shellChildren = providers
    ? `,\n  (outlet) => <${providers}>{outlet}</${providers}>,\n`
    : "\n"

  return [
    BANNER,
    imports.join("\n"),
    "",
    `export const Route = createRootRoute(\n  ${configLiteral}${shellChildren})`,
    "",
  ].join("\n")
}

/* =============================================================================
 * ROUTER
 * ============================================================================= */

//router keys nativ consumes itself — never spread into the generated createRouter.
const NON_CREATE_ROUTER_KEYS = new Set<string>([
  "memoryHistoryInStandalone",
  ...ROUTER_BUILD_KEYS,
])

function renderRouterGen(config: NativAppConfig): string {
  const router = config.router

  const lines: string[] = ["    routeTree,"]
  //memory history in standalone is opt-in (default off) — overriding the router
  //history is a real behavior change, so require the config to ask for it.
  if (router.memoryHistoryInStandalone)
    lines.push("    history: standaloneMemoryHistory(),")
  //nativ owns not-found: `notFoundScreen` renders at the root, so root mode is
  //the framework's opinion — injected here, still overridable via router config.
  if (!("notFoundMode" in router)) lines.push('    notFoundMode: "root",')
  //spread the runtime createRouter options — skip nativ's own keys and the
  //build-time generator paths (those configure the vite plugin, not createRouter).
  for (const [key, value] of Object.entries(router)) {
    if (NON_CREATE_ROUTER_KEYS.has(key)) continue
    lines.push(`    ${key}: ${serializeValue(value)},`)
  }

  const imports = [
    `import { standaloneMemoryHistory } from "@repo/nativ/shell"`,
    `import { createRouter } from "@tanstack/react-router"`,
    `import { routeTree } from "./routing/routeTree.gen"`,
  ]

  return [
    BANNER,
    imports.join("\n"),
    "",
    "export function getRouter() {",
    "  return createRouter({",
    lines.join("\n"),
    "  })",
    "}",
    "",
    'declare module "@tanstack/react-router" {',
    "  interface Register {",
    "    router: ReturnType<typeof getRouter>",
    "  }",
    "}",
    "",
  ].join("\n")
}

/* =============================================================================
 * HELPERS
 * ============================================================================= */

/** Add a default import for a present component thunk; return its local name. */
function importThunk(
  config: NativAppConfig,
  field:
    | "splashScreen"
    | "orientationGuardScreen"
    | "notFoundScreen"
    | "providers",
  localName: string,
  imports: string[],
): string | null {
  const thunk = config[field]
  if (!thunk) return null
  const specifier = extractThunkSpecifier(field, thunk)
  imports.push(`import ${localName} from ${JSON.stringify(specifier)}`)
  return localName
}

/** `./src/styles/main.css` → `@/styles/main.css` (the app's own alias). */
function toAppAlias(stylesPath: string): string {
  return stylesPath.replace(/^\.\/src\//, "@/").replace(/^src\//, "@/")
}

function writeIfChanged(filePath: string, content: string): void {
  if (existsSync(filePath) && readFileSync(filePath, "utf8") === content)
    return
  mkdirSync(path.dirname(filePath), { recursive: true })
  writeFileSync(filePath, content)
}
